<?php

namespace Database\Seeders;

use App\Models\Company;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BackfillCompaniesSeeder extends Seeder
{
    public function run(): void
    {
        $companies = $this->getCompanies();
        $created = 0;
        $updated = 0;

        foreach ($companies as $data) {
            $slug = $data['slug'] ?? Str::slug($data['name']);
            $company = Company::updateOrCreate(
                ['slug' => $slug],
                array_merge($data, ['slug' => $slug])
            );
            if ($company->wasRecentlyCreated) {
                $created++;
            } else {
                $updated++;
            }
        }

        $this->command->info("Created: {$created}, Updated: {$updated}, Total: ".Company::count());
    }

    private function getCompanies(): array
    {
        return [
            // ===== REQUIRED NOTABLE STARTUPS =====
            ['name' => 'Stripe', 'website' => 'https://stripe.com', 'description' => 'Online payment processing platform for internet businesses', 'category' => 'fintech', 'founded_date' => '2010-01-01'],
            ['name' => 'Databricks', 'website' => 'https://databricks.com', 'description' => 'Unified analytics platform for data engineering and data science', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Canva', 'website' => 'https://canva.com', 'description' => 'Online design and visual communication platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Discord', 'website' => 'https://discord.com', 'description' => 'Voice, video, and text communication platform for communities', 'category' => 'consumer', 'founded_date' => '2015-01-01'],
            ['name' => 'Airtable', 'website' => 'https://airtable.com', 'description' => 'Cloud-based spreadsheet-database hybrid collaboration platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Miro', 'website' => 'https://miro.com', 'description' => 'Online collaborative whiteboard platform for teams', 'category' => 'enterprise', 'founded_date' => '2011-01-01'],
            ['name' => 'Loom', 'website' => 'https://loom.com', 'description' => 'Video messaging and screen recording for work', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Calendly', 'website' => 'https://calendly.com', 'description' => 'Scheduling automation platform for businesses', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Deel', 'website' => 'https://deel.com', 'description' => 'Global payroll and compliance platform for remote teams', 'category' => 'fintech', 'founded_date' => '2019-01-01'],
            ['name' => 'Rippling', 'website' => 'https://rippling.com', 'description' => 'Workforce management platform combining HR, IT, and finance', 'category' => 'enterprise', 'founded_date' => '2016-01-01'],
            ['name' => 'Plaid', 'website' => 'https://plaid.com', 'description' => 'Financial data connectivity platform linking apps to bank accounts', 'category' => 'fintech', 'founded_date' => '2013-01-01'],
            ['name' => 'Brex', 'website' => 'https://brex.com', 'description' => 'Corporate credit cards and spend management for startups', 'category' => 'fintech', 'founded_date' => '2017-01-01'],
            ['name' => 'Ramp', 'website' => 'https://ramp.com', 'description' => 'Corporate card and spend management platform', 'category' => 'fintech', 'founded_date' => '2019-01-01'],
            ['name' => 'Mercury', 'website' => 'https://mercury.com', 'description' => 'Banking and financial services for startups', 'category' => 'fintech', 'founded_date' => '2017-01-01'],
            ['name' => 'Carta', 'website' => 'https://carta.com', 'description' => 'Equity management and cap table platform', 'category' => 'fintech', 'founded_date' => '2012-01-01'],
            ['name' => 'AngelList', 'website' => 'https://angellist.com', 'description' => 'Platform for startups, investors, and job seekers', 'category' => 'fintech', 'founded_date' => '2010-01-01'],
            ['name' => 'Snyk', 'website' => 'https://snyk.io', 'description' => 'Developer security platform for finding and fixing vulnerabilities', 'category' => 'developer_tools', 'founded_date' => '2015-01-01'],
            ['name' => 'Datadog', 'website' => 'https://datadoghq.com', 'description' => 'Cloud monitoring and security platform', 'category' => 'developer_tools', 'founded_date' => '2010-01-01'],
            ['name' => 'HashiCorp', 'website' => 'https://hashicorp.com', 'description' => 'Cloud infrastructure automation software', 'category' => 'developer_tools', 'founded_date' => '2012-01-01'],
            ['name' => 'Confluent', 'website' => 'https://confluent.io', 'description' => 'Data streaming platform based on Apache Kafka', 'category' => 'developer_tools', 'founded_date' => '2014-01-01'],
            ['name' => 'Elastic', 'website' => 'https://elastic.co', 'description' => 'Search, observability, and security platform', 'category' => 'developer_tools', 'founded_date' => '2012-01-01'],
            ['name' => 'Scale AI', 'website' => 'https://scale.com', 'description' => 'Data labeling and AI infrastructure platform', 'category' => 'ai_ml', 'founded_date' => '2016-01-01'],
            ['name' => 'Hugging Face', 'website' => 'https://huggingface.co', 'description' => 'Open-source AI model hub and ML platform', 'category' => 'ai_ml', 'founded_date' => '2016-01-01'],
            ['name' => 'Stability AI', 'website' => 'https://stability.ai', 'description' => 'Open-source generative AI company behind Stable Diffusion', 'category' => 'ai_ml', 'founded_date' => '2019-01-01'],
            ['name' => 'Midjourney', 'website' => 'https://midjourney.com', 'description' => 'AI-powered image generation platform', 'category' => 'ai_ml', 'founded_date' => '2021-01-01'],
            ['name' => 'RunwayML', 'website' => 'https://runwayml.com', 'description' => 'AI-powered creative tools for video and content generation', 'category' => 'ai_ml', 'founded_date' => '2018-01-01', 'slug' => 'runwayml'],
            ['name' => 'Webflow', 'website' => 'https://webflow.com', 'description' => 'No-code website builder and CMS platform', 'category' => 'developer_tools', 'founded_date' => '2013-01-01'],
            ['name' => 'Retool', 'website' => 'https://retool.com', 'description' => 'Low-code platform for building internal tools', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'PostHog', 'website' => 'https://posthog.com', 'description' => 'Open-source product analytics and session recording platform', 'category' => 'developer_tools', 'founded_date' => '2020-01-01'],
            ['name' => 'Amplitude', 'website' => 'https://amplitude.com', 'description' => 'Digital analytics platform for product intelligence', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Vanta', 'website' => 'https://vanta.com', 'description' => 'Automated security and compliance platform', 'category' => 'enterprise', 'founded_date' => '2018-01-01'],
            ['name' => 'Drata', 'website' => 'https://drata.com', 'description' => 'Security and compliance automation platform', 'category' => 'enterprise', 'founded_date' => '2020-01-01'],
            ['name' => 'Wiz', 'website' => 'https://wiz.io', 'description' => 'Cloud security platform for modern infrastructure', 'category' => 'enterprise', 'founded_date' => '2020-01-01'],
            ['name' => 'Orca Security', 'website' => 'https://orca.security', 'description' => 'Agentless cloud security platform', 'category' => 'enterprise', 'founded_date' => '2019-01-01'],
            ['name' => 'SentinelOne', 'website' => 'https://sentinelone.com', 'description' => 'AI-powered cybersecurity platform for endpoint protection', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Klarna', 'website' => 'https://klarna.com', 'description' => 'Buy now, pay later payment services provider', 'category' => 'fintech', 'founded_date' => '2005-01-01'],
            ['name' => 'Revolut', 'website' => 'https://revolut.com', 'description' => 'Digital banking and financial services super app', 'category' => 'fintech', 'founded_date' => '2015-01-01'],
            ['name' => 'Monzo', 'website' => 'https://monzo.com', 'description' => 'UK-based digital bank with smart money management', 'category' => 'fintech', 'founded_date' => '2015-01-01'],
            ['name' => 'Wise', 'website' => 'https://wise.com', 'description' => 'International money transfer and multi-currency platform', 'category' => 'fintech', 'founded_date' => '2011-01-01'],
            ['name' => 'Nubank', 'website' => 'https://nubank.com.br', 'description' => 'Latin American digital bank and financial services platform', 'category' => 'fintech', 'founded_date' => '2013-01-01'],
            ['name' => 'Rappi', 'website' => 'https://rappi.com', 'description' => 'Latin American on-demand delivery super app', 'category' => 'consumer', 'founded_date' => '2015-01-01'],
            ['name' => 'Grab', 'website' => 'https://grab.com', 'description' => 'Southeast Asian super app for ride-hailing, delivery, and payments', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'GoTo', 'website' => 'https://goto.com', 'description' => 'Indonesian super app combining ride-hailing, e-commerce, and payments', 'category' => 'consumer', 'founded_date' => '2010-01-01'],
            ['name' => 'Swiggy', 'website' => 'https://swiggy.com', 'description' => 'Indian food and grocery delivery platform', 'category' => 'consumer', 'founded_date' => '2014-01-01'],

            // ===== A16Z PORTFOLIO (well-known) =====
            ['name' => 'Neeva', 'website' => 'https://neeva.com', 'description' => 'Ad-free private search engine', 'category' => 'consumer', 'founded_date' => '2019-01-01'],
            ['name' => 'Dbt Labs', 'website' => 'https://getdbt.com', 'description' => 'Analytics engineering platform for data transformation', 'category' => 'developer_tools', 'founded_date' => '2016-01-01'],
            ['name' => 'Ironclad', 'website' => 'https://ironcladapp.com', 'description' => 'Digital contract lifecycle management platform', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Roblox', 'website' => 'https://roblox.com', 'description' => 'Online gaming platform and game creation system', 'category' => 'consumer', 'founded_date' => '2004-01-01'],
            ['name' => 'Substack', 'website' => 'https://substack.com', 'description' => 'Platform for independent writers and newsletters', 'category' => 'consumer', 'founded_date' => '2017-01-01'],
            ['name' => 'GitHub', 'website' => 'https://github.com', 'description' => 'Code hosting platform for version control and collaboration', 'category' => 'developer_tools', 'founded_date' => '2008-01-01'],
            ['name' => 'Lyft', 'website' => 'https://lyft.com', 'description' => 'Ride-sharing transportation network company', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Slack', 'website' => 'https://slack.com', 'description' => 'Business communication and collaboration platform', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Instacart', 'website' => 'https://instacart.com', 'description' => 'Online grocery delivery and pickup service', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Pinterest', 'website' => 'https://pinterest.com', 'description' => 'Visual discovery and bookmarking platform', 'category' => 'consumer', 'founded_date' => '2010-01-01'],
            ['name' => 'Navan', 'website' => 'https://navan.com', 'description' => 'Corporate travel and expense management platform', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Honor', 'website' => 'https://joinhonor.com', 'description' => 'Home care technology and services platform', 'category' => 'healthcare', 'founded_date' => '2014-01-01'],
            ['name' => 'Sigma Computing', 'website' => 'https://sigmacomputing.com', 'description' => 'Cloud analytics and business intelligence platform', 'category' => 'enterprise', 'founded_date' => '2014-01-01'],
            ['name' => 'Coda', 'website' => 'https://coda.io', 'description' => 'All-in-one doc for teams combining documents and spreadsheets', 'category' => 'enterprise', 'founded_date' => '2014-01-01'],
            ['name' => 'Convoy', 'website' => 'https://convoy.com', 'description' => 'Digital freight network for trucking', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Dapper Labs', 'website' => 'https://dapperlabs.com', 'description' => 'Blockchain company behind NBA Top Shot and Flow', 'category' => 'consumer', 'founded_date' => '2018-01-01'],
            ['name' => 'Neumann Monson', 'slug' => 'replit', 'website' => 'https://replit.com', 'description' => 'Browser-based IDE and coding platform', 'category' => 'developer_tools', 'founded_date' => '2016-01-01'],

            // ===== SEQUOIA PORTFOLIO =====
            ['name' => 'Nubank', 'website' => 'https://nubank.com.br', 'description' => 'Latin American digital bank', 'category' => 'fintech', 'founded_date' => '2013-01-01'],
            ['name' => 'Zoom', 'website' => 'https://zoom.us', 'description' => 'Video communications and virtual meeting platform', 'category' => 'enterprise', 'founded_date' => '2011-01-01'],
            ['name' => 'Unity', 'website' => 'https://unity.com', 'description' => 'Real-time 3D development platform for games and applications', 'category' => 'developer_tools', 'founded_date' => '2004-01-01'],
            ['name' => 'Snowflake', 'website' => 'https://snowflake.com', 'description' => 'Cloud data warehouse and analytics platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Palo Alto Networks', 'website' => 'https://paloaltonetworks.com', 'description' => 'Cybersecurity platform for network and cloud security', 'category' => 'enterprise', 'founded_date' => '2005-01-01'],
            ['name' => 'Vinted', 'website' => 'https://vinted.com', 'description' => 'Online marketplace for secondhand fashion', 'category' => 'consumer', 'founded_date' => '2008-01-01'],
            ['name' => 'Wiz', 'website' => 'https://wiz.io', 'description' => 'Cloud security platform', 'category' => 'enterprise', 'founded_date' => '2020-01-01'],

            // ===== GREYLOCK PORTFOLIO =====
            ['name' => 'Coda', 'website' => 'https://coda.io', 'description' => 'All-in-one doc for teams', 'category' => 'enterprise', 'founded_date' => '2014-01-01'],
            ['name' => 'Abnormal Security', 'website' => 'https://abnormalsecurity.com', 'description' => 'AI-native email security platform', 'category' => 'enterprise', 'founded_date' => '2018-01-01'],
            ['name' => 'Airtable', 'website' => 'https://airtable.com', 'description' => 'Cloud collaboration platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Cleo', 'website' => 'https://meetcleo.com', 'description' => 'AI-powered financial assistant', 'category' => 'fintech', 'founded_date' => '2016-01-01'],
            ['name' => 'Demisto', 'website' => 'https://demisto.com', 'description' => 'Security orchestration and automated response platform', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Neeva', 'website' => 'https://neeva.com', 'description' => 'Ad-free private search engine', 'category' => 'consumer', 'founded_date' => '2019-01-01'],
            ['name' => 'Pano AI', 'website' => 'https://pano.ai', 'description' => 'AI-powered wildfire detection platform', 'category' => 'climate', 'founded_date' => '2020-01-01'],
            ['name' => 'Rubrik', 'website' => 'https://rubrik.com', 'description' => 'Cloud data management and enterprise backup', 'category' => 'enterprise', 'founded_date' => '2014-01-01'],
            ['name' => 'Workato', 'website' => 'https://workato.com', 'description' => 'Enterprise automation and integration platform', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],

            // ===== INDEX VENTURES PORTFOLIO =====
            ['name' => 'Figma', 'website' => 'https://figma.com', 'description' => 'Collaborative interface design tool', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Notion', 'website' => 'https://notion.so', 'description' => 'All-in-one workspace for notes, docs, and project management', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Plaid', 'website' => 'https://plaid.com', 'description' => 'Financial data connectivity platform', 'category' => 'fintech', 'founded_date' => '2013-01-01'],
            ['name' => 'Deliveroo', 'website' => 'https://deliveroo.com', 'description' => 'Online food delivery platform', 'category' => 'consumer', 'founded_date' => '2013-01-01'],
            ['name' => 'Roblox', 'website' => 'https://roblox.com', 'description' => 'Online gaming platform', 'category' => 'consumer', 'founded_date' => '2004-01-01'],
            ['name' => 'Bird', 'website' => 'https://bird.co', 'description' => 'Electric scooter sharing platform', 'category' => 'consumer', 'founded_date' => '2017-01-01'],
            ['name' => 'Adyen', 'website' => 'https://adyen.com', 'description' => 'Global payment processing platform', 'category' => 'fintech', 'founded_date' => '2006-01-01'],
            ['name' => 'HashiCorp', 'website' => 'https://hashicorp.com', 'description' => 'Cloud infrastructure automation', 'category' => 'developer_tools', 'founded_date' => '2012-01-01'],
            ['name' => 'Elastic', 'website' => 'https://elastic.co', 'description' => 'Search and analytics engine', 'category' => 'developer_tools', 'founded_date' => '2012-01-01'],

            // ===== BENCHMARK PORTFOLIO =====
            ['name' => 'Uber', 'website' => 'https://uber.com', 'description' => 'Ride-hailing and food delivery platform', 'category' => 'consumer', 'founded_date' => '2009-01-01'],
            ['name' => 'Snapchat', 'slug' => 'snap', 'website' => 'https://snap.com', 'description' => 'Camera and social media company', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'Stitch Fix', 'website' => 'https://stitchfix.com', 'description' => 'Online personal styling and fashion service', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'Zillow', 'website' => 'https://zillow.com', 'description' => 'Online real estate marketplace', 'category' => 'consumer', 'founded_date' => '2006-01-01'],
            ['name' => 'WeWork', 'website' => 'https://wework.com', 'description' => 'Co-working space and flexible office provider', 'category' => 'enterprise', 'founded_date' => '2010-01-01'],
            ['name' => 'New Relic', 'website' => 'https://newrelic.com', 'description' => 'Application performance monitoring and observability', 'category' => 'developer_tools', 'founded_date' => '2008-01-01'],
            ['name' => 'Zendesk', 'website' => 'https://zendesk.com', 'description' => 'Customer service and engagement platform', 'category' => 'enterprise', 'founded_date' => '2007-01-01'],

            // ===== ACCEL PORTFOLIO =====
            ['name' => 'CrowdStrike', 'website' => 'https://crowdstrike.com', 'description' => 'Cloud-delivered endpoint and workload protection', 'category' => 'enterprise', 'founded_date' => '2011-01-01'],
            ['name' => 'Atlassian', 'website' => 'https://atlassian.com', 'description' => 'Team collaboration and project management software', 'category' => 'enterprise', 'founded_date' => '2002-01-01'],
            ['name' => 'Qualtrics', 'website' => 'https://qualtrics.com', 'description' => 'Experience management and survey platform', 'category' => 'enterprise', 'founded_date' => '2002-01-01'],
            ['name' => 'Freshworks', 'website' => 'https://freshworks.com', 'description' => 'Cloud-based SaaS for customer and employee engagement', 'category' => 'enterprise', 'founded_date' => '2010-01-01'],
            ['name' => 'Webflow', 'website' => 'https://webflow.com', 'description' => 'Visual web development platform', 'category' => 'developer_tools', 'founded_date' => '2013-01-01'],
            ['name' => 'Miro', 'website' => 'https://miro.com', 'description' => 'Online collaborative whiteboard', 'category' => 'enterprise', 'founded_date' => '2011-01-01'],
            ['name' => '1Password', 'website' => 'https://1password.com', 'description' => 'Password manager and digital vault', 'category' => 'enterprise', 'founded_date' => '2005-01-01'],

            // ===== LIGHTSPEED VENTURE PARTNERS PORTFOLIO =====
            ['name' => 'Rubrik', 'website' => 'https://rubrik.com', 'description' => 'Cloud data management and backup', 'category' => 'enterprise', 'founded_date' => '2014-01-01'],
            ['name' => 'Grafana Labs', 'website' => 'https://grafana.com', 'description' => 'Open-source analytics and monitoring platform', 'category' => 'developer_tools', 'founded_date' => '2014-01-01'],
            ['name' => 'OwnBackup', 'website' => 'https://ownbackup.com', 'description' => 'Cloud-to-cloud data backup and recovery', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Navan', 'website' => 'https://navan.com', 'description' => 'Travel and expense management', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Darwinbox', 'website' => 'https://darwinbox.com', 'description' => 'HR tech platform for enterprises', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Turing', 'website' => 'https://turing.com', 'description' => 'AI-powered tech talent platform', 'category' => 'enterprise', 'founded_date' => '2018-01-01'],
            ['name' => 'Indian Energy Exchange', 'slug' => 'multi-ai', 'website' => 'https://multi.ai', 'description' => 'Multi-agent AI orchestration platform', 'category' => 'ai_ml', 'founded_date' => '2020-01-01'],

            // ===== FOUNDERS FUND PORTFOLIO =====
            ['name' => 'SpaceX', 'website' => 'https://spacex.com', 'description' => 'Aerospace manufacturer and space transportation company', 'category' => 'space', 'founded_date' => '2002-01-01'],
            ['name' => 'Palantir', 'website' => 'https://palantir.com', 'description' => 'Big data analytics and software platform', 'category' => 'enterprise', 'founded_date' => '2003-01-01'],
            ['name' => 'Anduril Industries', 'website' => 'https://anduril.com', 'description' => 'Defense technology and autonomous systems', 'category' => 'defense', 'founded_date' => '2017-01-01'],
            ['name' => 'Neuralink', 'website' => 'https://neuralink.com', 'description' => 'Brain-computer interface technology', 'category' => 'healthcare', 'founded_date' => '2016-01-01'],
            ['name' => 'Oscar Health', 'website' => 'https://hioscar.com', 'description' => 'Technology-focused health insurance company', 'category' => 'healthcare', 'founded_date' => '2012-01-01'],
            ['name' => 'Relativity Space', 'website' => 'https://relativityspace.com', 'description' => '3D-printed rocket manufacturer', 'category' => 'space', 'founded_date' => '2015-01-01'],

            // ===== KLEINER PERKINS PORTFOLIO =====
            ['name' => 'Impossible Foods', 'website' => 'https://impossiblefoods.com', 'description' => 'Plant-based meat alternative company', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'Figma', 'website' => 'https://figma.com', 'description' => 'Collaborative design tool', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Rippling', 'website' => 'https://rippling.com', 'description' => 'Unified HR, IT, and finance platform', 'category' => 'enterprise', 'founded_date' => '2016-01-01'],

            // ===== YC NOTABLE COMPANIES =====
            ['name' => 'Airbnb', 'website' => 'https://airbnb.com', 'description' => 'Online marketplace for short-term home rentals', 'category' => 'consumer', 'founded_date' => '2008-01-01'],
            ['name' => 'DoorDash', 'website' => 'https://doordash.com', 'description' => 'Food delivery and logistics platform', 'category' => 'consumer', 'founded_date' => '2013-01-01'],
            ['name' => 'Gusto', 'website' => 'https://gusto.com', 'description' => 'Payroll, benefits, and HR platform for small businesses', 'category' => 'fintech', 'founded_date' => '2011-01-01'],
            ['name' => 'Segment', 'website' => 'https://segment.com', 'description' => 'Customer data platform and analytics infrastructure', 'category' => 'developer_tools', 'founded_date' => '2011-01-01'],
            ['name' => 'Zapier', 'website' => 'https://zapier.com', 'description' => 'Workflow automation connecting web applications', 'category' => 'enterprise', 'founded_date' => '2011-01-01'],
            ['name' => 'Faire', 'website' => 'https://faire.com', 'description' => 'Online wholesale marketplace for retailers', 'category' => 'enterprise', 'founded_date' => '2017-01-01'],
            ['name' => 'Podium', 'website' => 'https://podium.com', 'description' => 'Customer communication and payments platform', 'category' => 'enterprise', 'founded_date' => '2014-01-01'],
            ['name' => 'Fivetran', 'website' => 'https://fivetran.com', 'description' => 'Automated data integration and ELT platform', 'category' => 'developer_tools', 'founded_date' => '2012-01-01'],
            ['name' => 'Groww', 'website' => 'https://groww.in', 'description' => 'Indian investment and trading platform', 'category' => 'fintech', 'founded_date' => '2016-01-01'],
            ['name' => 'Zepto', 'website' => 'https://zeptonow.com', 'description' => 'Indian quick-commerce grocery delivery', 'category' => 'consumer', 'founded_date' => '2021-01-01'],
            ['name' => 'Razorpay', 'website' => 'https://razorpay.com', 'description' => 'Indian payment gateway and financial services', 'category' => 'fintech', 'founded_date' => '2014-01-01'],
            ['name' => 'Meesho', 'website' => 'https://meesho.com', 'description' => 'Indian social commerce platform', 'category' => 'consumer', 'founded_date' => '2015-01-01'],
            ['name' => 'Cleartax', 'website' => 'https://cleartax.in', 'description' => 'Indian tax filing and financial services platform', 'category' => 'fintech', 'founded_date' => '2011-01-01'],
            ['name' => 'Gupshup', 'website' => 'https://gupshup.io', 'description' => 'Conversational messaging platform', 'category' => 'enterprise', 'founded_date' => '2004-01-01'],
            ['name' => 'Whatnot', 'website' => 'https://whatnot.com', 'description' => 'Live shopping and marketplace platform', 'category' => 'consumer', 'founded_date' => '2019-01-01'],
            ['name' => 'Monzo', 'website' => 'https://monzo.com', 'description' => 'UK digital bank', 'category' => 'fintech', 'founded_date' => '2015-01-01'],

            // ===== FIRST ROUND CAPITAL PORTFOLIO =====
            ['name' => 'Notion', 'website' => 'https://notion.so', 'description' => 'All-in-one workspace', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Roblox', 'website' => 'https://roblox.com', 'description' => 'Online gaming platform', 'category' => 'consumer', 'founded_date' => '2004-01-01'],
            ['name' => 'Square', 'website' => 'https://squareup.com', 'description' => 'Financial services and digital payments platform', 'category' => 'fintech', 'founded_date' => '2009-01-01'],
            ['name' => 'Warby Parker', 'website' => 'https://warbyparker.com', 'description' => 'Direct-to-consumer eyewear brand', 'category' => 'consumer', 'founded_date' => '2010-01-01'],
            ['name' => 'Clover Health', 'website' => 'https://cloverhealth.com', 'description' => 'Technology-driven health insurance', 'category' => 'healthcare', 'founded_date' => '2014-01-01'],
            ['name' => 'Flatiron Health', 'website' => 'https://flatironhealth.com', 'description' => 'Oncology-focused health technology company', 'category' => 'healthcare', 'founded_date' => '2012-01-01'],
            ['name' => 'Looker', 'website' => 'https://looker.com', 'description' => 'Business intelligence and data analytics platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],

            // ===== USV PORTFOLIO (from scrape) =====
            ['name' => 'Dune Analytics', 'website' => 'https://dune.com', 'description' => 'Community-first crypto analytics platform', 'category' => 'fintech', 'founded_date' => '2018-01-01'],
            ['name' => 'Cloudflare', 'website' => 'https://cloudflare.com', 'description' => 'Web infrastructure and security company', 'category' => 'developer_tools', 'founded_date' => '2009-01-01'],
            ['name' => 'Twilio', 'website' => 'https://twilio.com', 'description' => 'Cloud communications platform for building SMS, voice, and messaging apps', 'category' => 'developer_tools', 'founded_date' => '2008-01-01'],
            ['name' => 'Coinbase', 'website' => 'https://coinbase.com', 'description' => 'Cryptocurrency exchange and platform', 'category' => 'fintech', 'founded_date' => '2012-01-01'],
            ['name' => 'MongoDB', 'website' => 'https://mongodb.com', 'description' => 'NoSQL database platform for modern applications', 'category' => 'developer_tools', 'founded_date' => '2007-01-01'],
            ['name' => 'DuckDuckGo', 'website' => 'https://duckduckgo.com', 'description' => 'Privacy-focused internet search engine', 'category' => 'consumer', 'founded_date' => '2008-01-01'],
            ['name' => 'Duolingo', 'website' => 'https://duolingo.com', 'description' => 'Language learning platform and app', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'Kickstarter', 'website' => 'https://kickstarter.com', 'description' => 'Crowdfunding platform for creative projects', 'category' => 'consumer', 'founded_date' => '2009-01-01'],
            ['name' => 'Stack Overflow', 'website' => 'https://stackoverflow.com', 'description' => 'Q&A platform for developers', 'category' => 'developer_tools', 'founded_date' => '2008-01-01'],
            ['name' => 'SoundCloud', 'website' => 'https://soundcloud.com', 'description' => 'Audio streaming and music sharing platform', 'category' => 'consumer', 'founded_date' => '2007-01-01'],
            ['name' => 'Etsy', 'website' => 'https://etsy.com', 'description' => 'Online marketplace for handmade and vintage goods', 'category' => 'consumer', 'founded_date' => '2005-01-01'],
            ['name' => 'Farcaster', 'website' => 'https://farcaster.xyz', 'description' => 'Sufficiently decentralized social network protocol', 'category' => 'consumer', 'founded_date' => '2020-01-01'],
            ['name' => 'Hume AI', 'website' => 'https://hume.ai', 'description' => 'AI models aligned with human well-being and emotional understanding', 'category' => 'ai_ml', 'founded_date' => '2021-01-01'],
            ['name' => 'Polygon', 'website' => 'https://polygon.technology', 'description' => 'Ethereum scaling and infrastructure platform', 'category' => 'fintech', 'founded_date' => '2017-01-01'],
            ['name' => 'Justworks', 'website' => 'https://justworks.com', 'description' => 'Payroll, benefits, HR, and compliance platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Codecademy', 'website' => 'https://codecademy.com', 'description' => 'Interactive online coding education platform', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'Shippo', 'website' => 'https://goshippo.com', 'description' => 'Shipping API for e-commerce businesses', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Teamshares', 'website' => 'https://teamshares.com', 'description' => 'Employee ownership platform for small businesses', 'category' => 'fintech', 'founded_date' => '2019-01-01'],
            ['name' => 'Consensus', 'website' => 'https://consensus.app', 'description' => 'AI-powered academic research search engine', 'category' => 'ai_ml', 'founded_date' => '2021-01-01'],
            ['name' => 'Arweave', 'website' => 'https://arweave.org', 'description' => 'Permanent decentralized data storage protocol', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],

            // ===== FLOODGATE PORTFOLIO =====
            ['name' => 'Twitch', 'website' => 'https://twitch.tv', 'description' => 'Live streaming platform for gaming and content', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'Lyft', 'website' => 'https://lyft.com', 'description' => 'Ride-sharing platform', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Refinery29', 'website' => 'https://refinery29.com', 'description' => 'Digital media and entertainment company for women', 'category' => 'consumer', 'founded_date' => '2005-01-01'],
            ['name' => 'Outschool', 'website' => 'https://outschool.com', 'description' => 'Online marketplace for live kids classes', 'category' => 'consumer', 'founded_date' => '2015-01-01'],

            // ===== LUX CAPITAL PORTFOLIO =====
            ['name' => 'Anduril Industries', 'website' => 'https://anduril.com', 'description' => 'Defense technology company', 'category' => 'defense', 'founded_date' => '2017-01-01'],
            ['name' => 'Eikon Therapeutics', 'website' => 'https://eikontx.com', 'description' => 'Drug discovery using super-resolution microscopy', 'category' => 'healthcare', 'founded_date' => '2019-01-01'],
            ['name' => 'Sarcos Robotics', 'website' => 'https://sarcos.com', 'description' => 'Industrial robotic systems and exoskeletons', 'category' => 'robotics', 'founded_date' => '2015-01-01'],
            ['name' => 'Machina Labs', 'website' => 'https://machinalabs.ai', 'description' => 'AI-driven robotic manufacturing', 'category' => 'robotics', 'founded_date' => '2019-01-01'],
            ['name' => 'Saildrone', 'website' => 'https://saildrone.com', 'description' => 'Autonomous ocean-going drones for data collection', 'category' => 'climate', 'founded_date' => '2012-01-01'],

            // ===== ADDITIONAL WELL-KNOWN STARTUPS (2018+) =====
            // AI/ML
            ['name' => 'Cohere', 'website' => 'https://cohere.com', 'description' => 'Enterprise AI platform for natural language processing', 'category' => 'ai_ml', 'founded_date' => '2019-01-01'],
            ['name' => 'Anthropic', 'website' => 'https://anthropic.com', 'description' => 'AI safety company building reliable and interpretable AI', 'category' => 'ai_ml', 'founded_date' => '2021-01-01'],
            ['name' => 'OpenAI', 'website' => 'https://openai.com', 'description' => 'AI research and deployment company', 'category' => 'ai_ml', 'founded_date' => '2015-01-01'],
            ['name' => 'Mistral AI', 'website' => 'https://mistral.ai', 'description' => 'French AI company building open-weight foundation models', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Adept', 'website' => 'https://adept.ai', 'description' => 'AI research lab building useful general intelligence', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Jasper', 'website' => 'https://jasper.ai', 'description' => 'AI content creation platform for marketing', 'category' => 'ai_ml', 'founded_date' => '2021-01-01'],
            ['name' => 'Writer', 'website' => 'https://writer.com', 'description' => 'AI writing and content platform for enterprises', 'category' => 'ai_ml', 'founded_date' => '2020-01-01'],
            ['name' => 'Inflection AI', 'website' => 'https://inflection.ai', 'description' => 'Personal AI assistant company', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Character.AI', 'website' => 'https://character.ai', 'description' => 'AI chatbot platform with customizable characters', 'category' => 'ai_ml', 'founded_date' => '2021-01-01'],
            ['name' => 'Glean', 'website' => 'https://glean.com', 'description' => 'AI-powered enterprise search and knowledge management', 'category' => 'ai_ml', 'founded_date' => '2019-01-01'],
            ['name' => 'Perplexity', 'website' => 'https://perplexity.ai', 'description' => 'AI-powered answer engine and search', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Pika', 'website' => 'https://pika.art', 'description' => 'AI video generation platform', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'ElevenLabs', 'website' => 'https://elevenlabs.io', 'description' => 'AI voice synthesis and text-to-speech platform', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Suno', 'website' => 'https://suno.com', 'description' => 'AI music generation platform', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Udio', 'website' => 'https://udio.com', 'description' => 'AI-powered music creation tool', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Together AI', 'website' => 'https://together.ai', 'description' => 'Cloud platform for training and running AI models', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Replicate', 'website' => 'https://replicate.com', 'description' => 'Platform to run ML models in the cloud via API', 'category' => 'ai_ml', 'founded_date' => '2019-01-01'],
            ['name' => 'Weights & Biases', 'website' => 'https://wandb.ai', 'description' => 'ML experiment tracking and model management', 'category' => 'ai_ml', 'founded_date' => '2017-01-01'],
            ['name' => 'Labelbox', 'website' => 'https://labelbox.com', 'description' => 'Data labeling and annotation platform for AI', 'category' => 'ai_ml', 'founded_date' => '2018-01-01'],
            ['name' => 'Deepgram', 'website' => 'https://deepgram.com', 'description' => 'AI speech recognition and understanding platform', 'category' => 'ai_ml', 'founded_date' => '2015-01-01'],
            ['name' => 'Synthesia', 'website' => 'https://synthesia.io', 'description' => 'AI video generation platform with virtual avatars', 'category' => 'ai_ml', 'founded_date' => '2017-01-01'],
            ['name' => 'Harvey', 'website' => 'https://harvey.ai', 'description' => 'AI assistant for legal professionals', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Cognition', 'website' => 'https://cognition.ai', 'description' => 'AI software engineering with Devin', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Poolside', 'website' => 'https://poolside.ai', 'description' => 'AI-powered software development assistant', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Magic', 'website' => 'https://magic.dev', 'description' => 'AI code generation with long context windows', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Galileo AI', 'website' => 'https://galileo-ai.com', 'description' => 'AI-powered UI design generation tool', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Ideogram', 'website' => 'https://ideogram.ai', 'description' => 'AI image generation with text rendering', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Luma AI', 'website' => 'https://lumalabs.ai', 'description' => 'AI-powered 3D capture and generation', 'category' => 'ai_ml', 'founded_date' => '2021-01-01'],
            ['name' => 'Groq', 'website' => 'https://groq.com', 'description' => 'AI inference accelerator hardware and cloud', 'category' => 'ai_ml', 'founded_date' => '2016-01-01'],
            ['name' => 'Cerebras Systems', 'website' => 'https://cerebras.net', 'description' => 'AI compute hardware with wafer-scale chips', 'category' => 'ai_ml', 'founded_date' => '2016-01-01'],
            ['name' => 'CoreWeave', 'slug' => 'coreweave', 'website' => 'https://coreweave.com', 'description' => 'GPU cloud provider for AI workloads', 'category' => 'ai_ml', 'founded_date' => '2017-01-01'],
            ['name' => 'Lambda', 'website' => 'https://lambdalabs.com', 'description' => 'GPU cloud computing for deep learning', 'category' => 'ai_ml', 'founded_date' => '2012-01-01'],
            ['name' => 'Baseten', 'website' => 'https://baseten.co', 'description' => 'ML model deployment and inference infrastructure', 'category' => 'ai_ml', 'founded_date' => '2019-01-01'],

            // Developer Tools
            ['name' => 'Vercel', 'website' => 'https://vercel.com', 'description' => 'Frontend cloud platform for web deployment', 'category' => 'developer_tools', 'founded_date' => '2015-01-01'],
            ['name' => 'Supabase', 'website' => 'https://supabase.com', 'description' => 'Open-source Firebase alternative with PostgreSQL', 'category' => 'developer_tools', 'founded_date' => '2020-01-01'],
            ['name' => 'PlanetScale', 'website' => 'https://planetscale.com', 'description' => 'Serverless MySQL-compatible database platform', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Railway', 'website' => 'https://railway.app', 'description' => 'Infrastructure platform for deploying apps', 'category' => 'developer_tools', 'founded_date' => '2020-01-01'],
            ['name' => 'Render', 'website' => 'https://render.com', 'description' => 'Cloud platform for building and running apps', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Fly.io', 'website' => 'https://fly.io', 'description' => 'Platform for running full-stack apps close to users', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'Neon', 'website' => 'https://neon.tech', 'description' => 'Serverless PostgreSQL database platform', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],
            ['name' => 'Turso', 'website' => 'https://turso.tech', 'description' => 'Edge database built on libSQL', 'category' => 'developer_tools', 'founded_date' => '2022-01-01'],
            ['name' => 'Resend', 'website' => 'https://resend.com', 'description' => 'Email API for developers', 'category' => 'developer_tools', 'founded_date' => '2022-01-01'],
            ['name' => 'Linear', 'website' => 'https://linear.app', 'description' => 'Project management tool for software teams', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Raycast', 'website' => 'https://raycast.com', 'description' => 'Productivity launcher and developer tool for macOS', 'category' => 'developer_tools', 'founded_date' => '2020-01-01'],
            ['name' => 'Warp', 'website' => 'https://warp.dev', 'description' => 'Modern terminal with AI-powered features', 'category' => 'developer_tools', 'founded_date' => '2020-01-01'],
            ['name' => 'Cursor', 'website' => 'https://cursor.sh', 'description' => 'AI-powered code editor', 'category' => 'developer_tools', 'founded_date' => '2022-01-01'],
            ['name' => 'Replit', 'website' => 'https://replit.com', 'description' => 'Browser-based IDE and coding platform', 'category' => 'developer_tools', 'founded_date' => '2016-01-01'],
            ['name' => 'GitLab', 'website' => 'https://gitlab.com', 'description' => 'DevOps platform for software development lifecycle', 'category' => 'developer_tools', 'founded_date' => '2011-01-01'],
            ['name' => 'LaunchDarkly', 'website' => 'https://launchdarkly.com', 'description' => 'Feature management and feature flag platform', 'category' => 'developer_tools', 'founded_date' => '2014-01-01'],
            ['name' => 'Postman', 'website' => 'https://postman.com', 'description' => 'API development and testing platform', 'category' => 'developer_tools', 'founded_date' => '2014-01-01'],
            ['name' => 'Temporal', 'website' => 'https://temporal.io', 'description' => 'Durable execution platform for distributed systems', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Cockroach Labs', 'website' => 'https://cockroachlabs.com', 'description' => 'Distributed SQL database (CockroachDB)', 'category' => 'developer_tools', 'founded_date' => '2015-01-01'],
            ['name' => 'Prisma', 'website' => 'https://prisma.io', 'description' => 'Next-generation ORM for Node.js and TypeScript', 'category' => 'developer_tools', 'founded_date' => '2016-01-01'],
            ['name' => 'Stytch', 'website' => 'https://stytch.com', 'description' => 'Passwordless authentication and identity platform', 'category' => 'developer_tools', 'founded_date' => '2020-01-01'],
            ['name' => 'Clerk', 'website' => 'https://clerk.com', 'description' => 'Authentication and user management for developers', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'WorkOS', 'website' => 'https://workos.com', 'description' => 'Enterprise-ready authentication and directory sync APIs', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Sentry', 'website' => 'https://sentry.io', 'description' => 'Application monitoring and error tracking', 'category' => 'developer_tools', 'founded_date' => '2012-01-01'],
            ['name' => 'Doppler', 'website' => 'https://doppler.com', 'description' => 'Secret management platform for developers', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Buildkite', 'website' => 'https://buildkite.com', 'description' => 'CI/CD platform for software development', 'category' => 'developer_tools', 'founded_date' => '2013-01-01'],
            ['name' => 'Planetscale', 'slug' => 'planetscale', 'website' => 'https://planetscale.com', 'description' => 'MySQL-compatible serverless database', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Weaviate', 'website' => 'https://weaviate.io', 'description' => 'Open-source vector database for AI applications', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Pinecone', 'website' => 'https://pinecone.io', 'description' => 'Vector database for machine learning applications', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Hasura', 'website' => 'https://hasura.io', 'description' => 'Instant GraphQL and REST APIs on databases', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'Airbyte', 'website' => 'https://airbyte.com', 'description' => 'Open-source data integration and ELT platform', 'category' => 'developer_tools', 'founded_date' => '2020-01-01'],
            ['name' => 'Rudderstack', 'website' => 'https://rudderstack.com', 'description' => 'Customer data platform for developers', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Statsig', 'website' => 'https://statsig.com', 'description' => 'Feature gating and experimentation platform', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],

            // Enterprise / SaaS
            ['name' => 'Notion', 'website' => 'https://notion.so', 'description' => 'All-in-one workspace', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'ClickUp', 'website' => 'https://clickup.com', 'description' => 'All-in-one productivity and project management platform', 'category' => 'enterprise', 'founded_date' => '2017-01-01'],
            ['name' => 'Monday.com', 'website' => 'https://monday.com', 'description' => 'Work operating system for team collaboration', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Asana', 'website' => 'https://asana.com', 'description' => 'Work management platform for teams', 'category' => 'enterprise', 'founded_date' => '2008-01-01'],
            ['name' => 'ServiceTitan', 'website' => 'https://servicetitan.com', 'description' => 'Software platform for home and commercial service businesses', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Toast', 'website' => 'https://pos.toasttab.com', 'description' => 'Restaurant management and POS platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Gong', 'website' => 'https://gong.io', 'description' => 'Revenue intelligence platform using conversation AI', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Hightouch', 'website' => 'https://hightouch.com', 'description' => 'Reverse ETL and data activation platform', 'category' => 'enterprise', 'founded_date' => '2020-01-01'],
            ['name' => 'Attio', 'website' => 'https://attio.com', 'description' => 'Next-generation CRM platform', 'category' => 'enterprise', 'founded_date' => '2019-01-01'],
            ['name' => 'Clay', 'website' => 'https://clay.com', 'description' => 'Data enrichment and outbound automation platform', 'category' => 'enterprise', 'founded_date' => '2017-01-01'],
            ['name' => 'Deel', 'website' => 'https://deel.com', 'description' => 'Global HR and payroll platform', 'category' => 'enterprise', 'founded_date' => '2019-01-01'],
            ['name' => 'Lattice', 'website' => 'https://lattice.com', 'description' => 'People management platform for HR teams', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Gusto', 'website' => 'https://gusto.com', 'description' => 'HR, payroll, and benefits platform', 'category' => 'enterprise', 'founded_date' => '2011-01-01'],
            ['name' => 'Remote', 'website' => 'https://remote.com', 'description' => 'Global employment and payroll platform', 'category' => 'enterprise', 'founded_date' => '2019-01-01'],
            ['name' => 'Oyster', 'website' => 'https://oysterhr.com', 'description' => 'Distributed hiring and HR platform', 'category' => 'enterprise', 'founded_date' => '2020-01-01'],
            ['name' => 'Papaya Global', 'website' => 'https://papayaglobal.com', 'description' => 'Global payroll and workforce management', 'category' => 'enterprise', 'founded_date' => '2016-01-01'],
            ['name' => 'Calendly', 'website' => 'https://calendly.com', 'description' => 'Meeting scheduling automation', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Loom', 'website' => 'https://loom.com', 'description' => 'Video messaging for work', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Canva', 'website' => 'https://canva.com', 'description' => 'Visual communication platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Grammarly', 'website' => 'https://grammarly.com', 'description' => 'AI-powered writing assistant', 'category' => 'enterprise', 'founded_date' => '2009-01-01'],
            ['name' => 'Aiven', 'website' => 'https://aiven.io', 'description' => 'Managed open-source cloud data infrastructure', 'category' => 'developer_tools', 'founded_date' => '2016-01-01'],
            ['name' => 'Cribl', 'website' => 'https://cribl.io', 'description' => 'Observability data pipeline platform', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Tailscale', 'website' => 'https://tailscale.com', 'description' => 'Zero-config VPN and mesh networking', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Tines', 'website' => 'https://tines.com', 'description' => 'Security workflow automation platform', 'category' => 'enterprise', 'founded_date' => '2018-01-01'],
            ['name' => 'Immuta', 'website' => 'https://immuta.com', 'description' => 'Data access control and governance platform', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Island', 'website' => 'https://island.io', 'description' => 'Enterprise browser for secure work', 'category' => 'enterprise', 'founded_date' => '2020-01-01'],
            ['name' => 'Material Security', 'website' => 'https://material.security', 'description' => 'Email security and data governance', 'category' => 'enterprise', 'founded_date' => '2017-01-01'],
            ['name' => 'Lacework', 'website' => 'https://lacework.com', 'description' => 'Cloud security and threat detection platform', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],

            // Fintech
            ['name' => 'Chime', 'website' => 'https://chime.com', 'description' => 'Mobile-first banking platform', 'category' => 'fintech', 'founded_date' => '2012-01-01'],
            ['name' => 'Marqeta', 'website' => 'https://marqeta.com', 'description' => 'Modern card issuing and payment platform', 'category' => 'fintech', 'founded_date' => '2010-01-01'],
            ['name' => 'Robinhood', 'website' => 'https://robinhood.com', 'description' => 'Commission-free stock trading platform', 'category' => 'fintech', 'founded_date' => '2013-01-01'],
            ['name' => 'Affirm', 'website' => 'https://affirm.com', 'description' => 'Buy now pay later financial platform', 'category' => 'fintech', 'founded_date' => '2012-01-01'],
            ['name' => 'Checkout.com', 'website' => 'https://checkout.com', 'description' => 'Global payment processing platform', 'category' => 'fintech', 'founded_date' => '2012-01-01'],
            ['name' => 'N26', 'website' => 'https://n26.com', 'description' => 'German mobile-first digital bank', 'category' => 'fintech', 'founded_date' => '2013-01-01'],
            ['name' => 'Nuvei', 'website' => 'https://nuvei.com', 'description' => 'Global payment technology company', 'category' => 'fintech', 'founded_date' => '2003-01-01'],
            ['name' => 'Flutterwave', 'website' => 'https://flutterwave.com', 'description' => 'African payment infrastructure company', 'category' => 'fintech', 'founded_date' => '2016-01-01'],
            ['name' => 'MoonPay', 'website' => 'https://moonpay.com', 'description' => 'Crypto payments infrastructure', 'category' => 'fintech', 'founded_date' => '2019-01-01'],
            ['name' => 'Stax', 'website' => 'https://staxpayments.com', 'description' => 'Payment processing and business management', 'category' => 'fintech', 'founded_date' => '2014-01-01'],
            ['name' => 'Melio', 'website' => 'https://meliopayments.com', 'description' => 'B2B payments platform for small businesses', 'category' => 'fintech', 'founded_date' => '2018-01-01'],
            ['name' => 'Greenlight', 'website' => 'https://greenlight.com', 'description' => 'Debit card and financial literacy for kids', 'category' => 'fintech', 'founded_date' => '2014-01-01'],
            ['name' => 'Dave', 'website' => 'https://dave.com', 'description' => 'Banking app for financial health', 'category' => 'fintech', 'founded_date' => '2016-01-01'],
            ['name' => 'Pipe', 'website' => 'https://pipe.com', 'description' => 'Revenue-based financing platform for SaaS', 'category' => 'fintech', 'founded_date' => '2019-01-01'],
            ['name' => 'TrueLayer', 'website' => 'https://truelayer.com', 'description' => 'Open banking payments network', 'category' => 'fintech', 'founded_date' => '2016-01-01'],
            ['name' => 'Pleo', 'website' => 'https://pleo.io', 'description' => 'Smart company spending and expense management', 'category' => 'fintech', 'founded_date' => '2015-01-01'],
            ['name' => 'Zepz', 'website' => 'https://zepz.com', 'description' => 'International money transfer (WorldRemit/Sendwave)', 'category' => 'fintech', 'founded_date' => '2010-01-01'],
            ['name' => 'Chipper Cash', 'website' => 'https://chippercash.com', 'description' => 'African cross-border payments app', 'category' => 'fintech', 'founded_date' => '2018-01-01'],
            ['name' => 'OPay', 'website' => 'https://opayweb.com', 'description' => 'Nigerian mobile payments platform', 'category' => 'fintech', 'founded_date' => '2018-01-01'],
            ['name' => 'Parafin', 'website' => 'https://parafin.com', 'description' => 'Embedded capital and financial products', 'category' => 'fintech', 'founded_date' => '2020-01-01'],
            ['name' => 'Unit', 'website' => 'https://unit.co', 'description' => 'Banking-as-a-service API platform', 'category' => 'fintech', 'founded_date' => '2019-01-01'],

            // Consumer
            ['name' => 'Spotify', 'website' => 'https://spotify.com', 'description' => 'Music and podcast streaming platform', 'category' => 'consumer', 'founded_date' => '2006-01-01'],
            ['name' => 'ByteDance', 'website' => 'https://bytedance.com', 'description' => 'Technology company behind TikTok', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Reddit', 'website' => 'https://reddit.com', 'description' => 'Social news and discussion platform', 'category' => 'consumer', 'founded_date' => '2005-01-01'],
            ['name' => 'Poshmark', 'website' => 'https://poshmark.com', 'description' => 'Social commerce marketplace for fashion', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'StockX', 'website' => 'https://stockx.com', 'description' => 'Online marketplace for sneakers and streetwear', 'category' => 'consumer', 'founded_date' => '2016-01-01'],
            ['name' => 'Fanatics', 'website' => 'https://fanatics.com', 'description' => 'Sports merchandise and digital sports platform', 'category' => 'consumer', 'founded_date' => '1995-01-01'],
            ['name' => 'Flexport', 'website' => 'https://flexport.com', 'description' => 'Technology-powered freight forwarder and logistics', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Goat', 'website' => 'https://goat.com', 'description' => 'Sneaker and apparel marketplace', 'category' => 'consumer', 'founded_date' => '2015-01-01'],
            ['name' => 'Getir', 'website' => 'https://getir.com', 'description' => 'Ultra-fast grocery delivery platform', 'category' => 'consumer', 'founded_date' => '2015-01-01'],
            ['name' => 'Gopuff', 'website' => 'https://gopuff.com', 'description' => 'Instant delivery platform for everyday essentials', 'category' => 'consumer', 'founded_date' => '2013-01-01'],
            ['name' => 'Gorillas', 'website' => 'https://gorillas.io', 'description' => 'Rapid grocery delivery service', 'category' => 'consumer', 'founded_date' => '2020-01-01'],
            ['name' => 'Flink', 'website' => 'https://goflink.com', 'description' => 'Quick commerce grocery delivery in Europe', 'category' => 'consumer', 'founded_date' => '2020-01-01'],
            ['name' => 'Nykaa', 'website' => 'https://nykaa.com', 'description' => 'Indian beauty and fashion e-commerce platform', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Zomato', 'website' => 'https://zomato.com', 'description' => 'Indian food delivery and restaurant discovery platform', 'category' => 'consumer', 'founded_date' => '2008-01-01'],
            ['name' => 'CRED', 'website' => 'https://cred.club', 'description' => 'Indian credit card rewards and payments app', 'category' => 'fintech', 'founded_date' => '2018-01-01'],
            ['name' => 'PhonePe', 'website' => 'https://phonepe.com', 'description' => 'Indian digital payments platform', 'category' => 'fintech', 'founded_date' => '2015-01-01'],
            ['name' => 'Dream11', 'website' => 'https://dream11.com', 'description' => 'Indian fantasy sports platform', 'category' => 'consumer', 'founded_date' => '2008-01-01'],
            ['name' => 'Shipt', 'website' => 'https://shipt.com', 'description' => 'Same-day delivery marketplace', 'category' => 'consumer', 'founded_date' => '2014-01-01'],
            ['name' => 'Calm', 'website' => 'https://calm.com', 'description' => 'Meditation and sleep wellness app', 'category' => 'healthcare', 'founded_date' => '2012-01-01'],
            ['name' => 'Headspace', 'website' => 'https://headspace.com', 'description' => 'Guided meditation and mindfulness app', 'category' => 'healthcare', 'founded_date' => '2010-01-01'],

            // Healthcare / Biotech
            ['name' => 'Devoted Health', 'website' => 'https://devoted.com', 'description' => 'Medicare Advantage health insurance', 'category' => 'healthcare', 'founded_date' => '2017-01-01'],
            ['name' => 'Ro', 'website' => 'https://ro.co', 'description' => 'Telehealth and direct-to-patient healthcare', 'category' => 'healthcare', 'founded_date' => '2017-01-01'],
            ['name' => 'Hims & Hers', 'website' => 'https://forhims.com', 'description' => 'Telehealth platform for health and wellness', 'category' => 'healthcare', 'founded_date' => '2017-01-01'],
            ['name' => 'Noom', 'website' => 'https://noom.com', 'description' => 'Behavior change and weight management platform', 'category' => 'healthcare', 'founded_date' => '2008-01-01'],
            ['name' => 'Tempus', 'website' => 'https://tempus.com', 'description' => 'Precision medicine and clinical data analytics', 'category' => 'healthcare', 'founded_date' => '2015-01-01'],
            ['name' => 'Olive AI', 'website' => 'https://oliveai.com', 'description' => 'AI automation for healthcare operations', 'category' => 'healthcare', 'founded_date' => '2012-01-01'],
            ['name' => 'Aledade', 'website' => 'https://aledade.com', 'description' => 'Value-based care platform for independent practices', 'category' => 'healthcare', 'founded_date' => '2014-01-01'],
            ['name' => 'Cityblock Health', 'website' => 'https://cityblock.com', 'description' => 'Healthcare for underserved urban communities', 'category' => 'healthcare', 'founded_date' => '2017-01-01'],
            ['name' => 'Color Health', 'website' => 'https://color.com', 'description' => 'Population health and genetic testing platform', 'category' => 'healthcare', 'founded_date' => '2013-01-01'],
            ['name' => 'Viz.ai', 'website' => 'https://viz.ai', 'description' => 'AI-powered disease detection and care coordination', 'category' => 'healthcare', 'founded_date' => '2016-01-01'],
            ['name' => 'Sword Health', 'website' => 'https://swordhealth.com', 'description' => 'AI-powered virtual physical therapy', 'category' => 'healthcare', 'founded_date' => '2015-01-01'],
            ['name' => 'Cerebral', 'website' => 'https://cerebral.com', 'description' => 'Online mental health treatment platform', 'category' => 'healthcare', 'founded_date' => '2020-01-01'],
            ['name' => 'Ginkgo Bioworks', 'website' => 'https://ginkgobioworks.com', 'description' => 'Cell programming and synthetic biology platform', 'category' => 'healthcare', 'founded_date' => '2008-01-01'],
            ['name' => 'Mammoth Biosciences', 'website' => 'https://mammothbiosci.com', 'description' => 'CRISPR-based diagnostics and therapeutics', 'category' => 'healthcare', 'founded_date' => '2017-01-01'],
            ['name' => 'Retro Biosciences', 'website' => 'https://retro.bio', 'description' => 'Longevity and cellular reprogramming research', 'category' => 'healthcare', 'founded_date' => '2021-01-01'],

            // Robotics
            ['name' => 'Figure AI', 'website' => 'https://figure.ai', 'description' => 'Humanoid robotics for labor automation', 'category' => 'robotics', 'founded_date' => '2022-01-01'],
            ['name' => '1X Technologies', 'website' => 'https://1x.tech', 'description' => 'Humanoid robotics for everyday tasks', 'category' => 'robotics', 'founded_date' => '2014-01-01'],
            ['name' => 'Nuro', 'website' => 'https://nuro.ai', 'description' => 'Autonomous delivery vehicles', 'category' => 'robotics', 'founded_date' => '2016-01-01'],
            ['name' => 'Waymo', 'website' => 'https://waymo.com', 'description' => 'Autonomous driving technology', 'category' => 'robotics', 'founded_date' => '2009-01-01'],
            ['name' => 'Cruise', 'website' => 'https://getcruise.com', 'description' => 'Self-driving car technology', 'category' => 'robotics', 'founded_date' => '2013-01-01'],
            ['name' => 'Aurora', 'website' => 'https://aurora.tech', 'description' => 'Self-driving technology for trucking and ride-hailing', 'category' => 'robotics', 'founded_date' => '2017-01-01'],
            ['name' => 'Boston Dynamics', 'website' => 'https://bostondynamics.com', 'description' => 'Advanced robotics for mobility and manipulation', 'category' => 'robotics', 'founded_date' => '1992-01-01'],
            ['name' => 'Agility Robotics', 'website' => 'https://agilityrobotics.com', 'description' => 'Bipedal robot (Digit) for logistics', 'category' => 'robotics', 'founded_date' => '2015-01-01'],
            ['name' => 'Apptronik', 'website' => 'https://apptronik.com', 'description' => 'Humanoid robot for industrial applications', 'category' => 'robotics', 'founded_date' => '2016-01-01'],
            ['name' => 'Skydio', 'website' => 'https://skydio.com', 'description' => 'Autonomous drone technology', 'category' => 'robotics', 'founded_date' => '2014-01-01'],
            ['name' => 'Shield AI', 'website' => 'https://shield.ai', 'description' => 'AI-piloted autonomous defense drones', 'category' => 'defense', 'founded_date' => '2015-01-01'],
            ['name' => 'Ghost Robotics', 'website' => 'https://ghostrobotics.io', 'description' => 'Legged robots for defense and enterprise', 'category' => 'robotics', 'founded_date' => '2015-01-01'],

            // Space
            ['name' => 'Blue Origin', 'website' => 'https://blueorigin.com', 'description' => 'Space launch and tourism company', 'category' => 'space', 'founded_date' => '2000-01-01'],
            ['name' => 'Rocket Lab', 'website' => 'https://rocketlabusa.com', 'description' => 'Small satellite launch services', 'category' => 'space', 'founded_date' => '2006-01-01'],
            ['name' => 'Planet Labs', 'website' => 'https://planet.com', 'description' => 'Earth observation satellite imagery', 'category' => 'space', 'founded_date' => '2010-01-01'],
            ['name' => 'Astra', 'website' => 'https://astra.com', 'description' => 'Small rocket launch services', 'category' => 'space', 'founded_date' => '2016-01-01'],
            ['name' => 'Vast', 'website' => 'https://vastspace.com', 'description' => 'Commercial space station development', 'category' => 'space', 'founded_date' => '2021-01-01'],
            ['name' => 'Stoke Space', 'website' => 'https://stokespace.com', 'description' => 'Fully reusable rocket development', 'category' => 'space', 'founded_date' => '2019-01-01'],

            // Climate / Energy
            ['name' => 'Redwood Materials', 'website' => 'https://redwoodmaterials.com', 'description' => 'Battery recycling and materials company', 'category' => 'climate', 'founded_date' => '2017-01-01'],
            ['name' => 'Form Energy', 'website' => 'https://formenergy.com', 'description' => 'Long-duration energy storage using iron-air batteries', 'category' => 'climate', 'founded_date' => '2017-01-01'],
            ['name' => 'Commonwealth Fusion Systems', 'website' => 'https://cfs.energy', 'description' => 'Fusion energy technology development', 'category' => 'climate', 'founded_date' => '2018-01-01'],
            ['name' => 'Helion Energy', 'website' => 'https://helionenergy.com', 'description' => 'Fusion power company', 'category' => 'climate', 'founded_date' => '2013-01-01'],
            ['name' => 'TAE Technologies', 'website' => 'https://tae.com', 'description' => 'Fusion energy and power management', 'category' => 'climate', 'founded_date' => '1998-01-01'],
            ['name' => 'QuantumScape', 'website' => 'https://quantumscape.com', 'description' => 'Solid-state lithium-metal battery technology', 'category' => 'climate', 'founded_date' => '2010-01-01'],
            ['name' => 'Rivian', 'website' => 'https://rivian.com', 'description' => 'Electric vehicle and adventure vehicle manufacturer', 'category' => 'climate', 'founded_date' => '2009-01-01'],
            ['name' => 'Lucid Motors', 'website' => 'https://lucidmotors.com', 'description' => 'Luxury electric vehicle manufacturer', 'category' => 'climate', 'founded_date' => '2007-01-01'],
            ['name' => 'Northvolt', 'website' => 'https://northvolt.com', 'description' => 'European battery cell manufacturer', 'category' => 'climate', 'founded_date' => '2016-01-01'],
            ['name' => 'Sila Nanotechnologies', 'website' => 'https://silanano.com', 'description' => 'Next-gen battery materials for EVs and electronics', 'category' => 'climate', 'founded_date' => '2011-01-01'],
            ['name' => 'Twelve', 'website' => 'https://twelve.co', 'description' => 'CO2 transformation into chemicals and fuels', 'category' => 'climate', 'founded_date' => '2015-01-01'],
            ['name' => 'Climeworks', 'website' => 'https://climeworks.com', 'description' => 'Direct air carbon capture and storage', 'category' => 'climate', 'founded_date' => '2009-01-01'],
            ['name' => 'Amp Robotics', 'website' => 'https://amprobotics.com', 'description' => 'AI-powered recycling robotics', 'category' => 'climate', 'founded_date' => '2014-01-01'],
            ['name' => 'Pachama', 'website' => 'https://pachama.com', 'description' => 'AI-verified carbon credits from forest projects', 'category' => 'climate', 'founded_date' => '2018-01-01'],

            // Defense
            ['name' => 'Palantir', 'website' => 'https://palantir.com', 'description' => 'Big data analytics for government and enterprise', 'category' => 'defense', 'founded_date' => '2003-01-01'],
            ['name' => 'Shield AI', 'website' => 'https://shield.ai', 'description' => 'AI-piloted autonomous systems for defense', 'category' => 'defense', 'founded_date' => '2015-01-01'],
            ['name' => 'Skydio', 'website' => 'https://skydio.com', 'description' => 'Autonomous drone technology', 'category' => 'defense', 'founded_date' => '2014-01-01'],
            ['name' => 'Hadrian', 'website' => 'https://hadrian.co', 'description' => 'Automated precision manufacturing for aerospace', 'category' => 'defense', 'founded_date' => '2020-01-01'],
            ['name' => 'Epirus', 'website' => 'https://epirusinc.com', 'description' => 'Directed energy and power management for defense', 'category' => 'defense', 'founded_date' => '2018-01-01'],
            ['name' => 'Saronic', 'website' => 'https://saronic.com', 'description' => 'Autonomous surface vessels for naval defense', 'category' => 'defense', 'founded_date' => '2022-01-01'],
            ['name' => 'Hermeus', 'website' => 'https://hermeus.com', 'description' => 'Hypersonic aircraft development', 'category' => 'defense', 'founded_date' => '2018-01-01'],

            // Additional notable startups
            ['name' => 'Talkdesk', 'website' => 'https://talkdesk.com', 'description' => 'AI-powered contact center platform', 'category' => 'enterprise', 'founded_date' => '2011-01-01'],
            ['name' => 'Cockroach Labs', 'website' => 'https://cockroachlabs.com', 'description' => 'Distributed SQL database', 'category' => 'developer_tools', 'founded_date' => '2015-01-01'],
            ['name' => 'Kong', 'website' => 'https://konghq.com', 'description' => 'API gateway and service connectivity platform', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'GitPod', 'website' => 'https://gitpod.io', 'description' => 'Cloud development environments', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Fermyon', 'website' => 'https://fermyon.com', 'description' => 'WebAssembly cloud platform', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],
            ['name' => 'Hex', 'website' => 'https://hex.tech', 'description' => 'Collaborative data workspace and analytics', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Preset', 'website' => 'https://preset.io', 'description' => 'Cloud-native data exploration (Apache Superset)', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Materialize', 'website' => 'https://materialize.com', 'description' => 'Streaming SQL database for real-time analytics', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'MotherDuck', 'website' => 'https://motherduck.com', 'description' => 'Serverless analytics powered by DuckDB', 'category' => 'developer_tools', 'founded_date' => '2022-01-01'],
            ['name' => 'Tigris Data', 'website' => 'https://tigrisdata.com', 'description' => 'Globally distributed object storage', 'category' => 'developer_tools', 'founded_date' => '2022-01-01'],
            ['name' => 'Buf', 'website' => 'https://buf.build', 'description' => 'Protocol Buffers management and API tooling', 'category' => 'developer_tools', 'founded_date' => '2020-01-01'],
            ['name' => 'Oso', 'website' => 'https://osohq.com', 'description' => 'Authorization as a service for developers', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Inngest', 'website' => 'https://inngest.com', 'description' => 'Event-driven serverless function orchestration', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],
            ['name' => 'Depot', 'website' => 'https://depot.dev', 'description' => 'Fast Docker container builds', 'category' => 'developer_tools', 'founded_date' => '2022-01-01'],
            ['name' => 'Zilliz', 'website' => 'https://zilliz.com', 'description' => 'Vector database company behind Milvus', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'Qdrant', 'website' => 'https://qdrant.tech', 'description' => 'Open-source vector similarity search engine', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],
            ['name' => 'Modal', 'website' => 'https://modal.com', 'description' => 'Serverless cloud for data and ML teams', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],
            ['name' => 'Dagger', 'website' => 'https://dagger.io', 'description' => 'Programmable CI/CD engine', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],
            ['name' => 'Trunk', 'website' => 'https://trunk.io', 'description' => 'Developer tools for code quality and CI', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],

            // ===== BATCH 2: MORE AI =====
            ['name' => 'Tavus', 'website' => 'https://tavus.io', 'description' => 'AI-powered personalized video generation', 'category' => 'ai_ml', 'founded_date' => '2020-01-01'],
            ['name' => 'Typeface', 'website' => 'https://typeface.ai', 'description' => 'Generative AI for enterprise content creation', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Tome', 'website' => 'https://tome.app', 'description' => 'AI-powered storytelling and presentation platform', 'category' => 'ai_ml', 'founded_date' => '2020-01-01'],
            ['name' => 'Mem', 'website' => 'https://mem.ai', 'description' => 'AI-powered knowledge management and notes', 'category' => 'ai_ml', 'founded_date' => '2020-01-01'],
            ['name' => 'Sierra', 'website' => 'https://sierra.ai', 'description' => 'Conversational AI for customer experience', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Contextual AI', 'website' => 'https://contextual.ai', 'description' => 'Enterprise RAG and language AI platform', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Reka', 'website' => 'https://reka.ai', 'description' => 'Multimodal AI model development', 'category' => 'ai_ml', 'founded_date' => '2023-01-01'],
            ['name' => 'Aleph Alpha', 'website' => 'https://aleph-alpha.com', 'description' => 'European sovereign AI company', 'category' => 'ai_ml', 'founded_date' => '2019-01-01'],
            ['name' => 'AI21 Labs', 'website' => 'https://ai21.com', 'description' => 'Enterprise AI writing and language platform', 'category' => 'ai_ml', 'founded_date' => '2017-01-01'],
            ['name' => 'Lightricks', 'website' => 'https://lightricks.com', 'description' => 'AI-powered creative tools and photo/video editing', 'category' => 'ai_ml', 'founded_date' => '2013-01-01'],
            ['name' => 'Moveworks', 'website' => 'https://moveworks.com', 'description' => 'AI copilot for enterprise IT support', 'category' => 'ai_ml', 'founded_date' => '2016-01-01'],
            ['name' => 'AssemblyAI', 'website' => 'https://assemblyai.com', 'description' => 'AI speech-to-text and audio intelligence API', 'category' => 'ai_ml', 'founded_date' => '2017-01-01'],
            ['name' => 'Unstructured', 'website' => 'https://unstructured.io', 'description' => 'Data preprocessing for LLM applications', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'LangChain', 'website' => 'https://langchain.com', 'description' => 'Framework for building LLM-powered applications', 'category' => 'ai_ml', 'founded_date' => '2022-01-01'],
            ['name' => 'Snorkel AI', 'website' => 'https://snorkel.ai', 'description' => 'Data-centric AI development platform', 'category' => 'ai_ml', 'founded_date' => '2019-01-01'],

            // ===== BATCH 2: MORE ENTERPRISE =====
            ['name' => 'Braze', 'website' => 'https://braze.com', 'description' => 'Customer engagement and marketing automation platform', 'category' => 'enterprise', 'founded_date' => '2011-01-01'],
            ['name' => 'Contentful', 'website' => 'https://contentful.com', 'description' => 'Composable content management platform', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Sanity', 'website' => 'https://sanity.io', 'description' => 'Composable content cloud and headless CMS', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'Hygraph', 'website' => 'https://hygraph.com', 'description' => 'Federated content platform (GraphCMS)', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'Storyblok', 'website' => 'https://storyblok.com', 'description' => 'Visual headless CMS for developers and marketers', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'Algolia', 'website' => 'https://algolia.com', 'description' => 'Search and discovery API platform', 'category' => 'developer_tools', 'founded_date' => '2012-01-01'],
            ['name' => 'Mux', 'website' => 'https://mux.com', 'description' => 'Video API and analytics infrastructure', 'category' => 'developer_tools', 'founded_date' => '2015-01-01'],
            ['name' => 'Mixpanel', 'website' => 'https://mixpanel.com', 'description' => 'Product analytics and user behavior tracking', 'category' => 'enterprise', 'founded_date' => '2009-01-01'],
            ['name' => 'Heap', 'website' => 'https://heap.io', 'description' => 'Digital insights platform with auto-capture analytics', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Census', 'website' => 'https://getcensus.com', 'description' => 'Reverse ETL data activation platform', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Monte Carlo', 'website' => 'https://montecarlodata.com', 'description' => 'Data observability platform', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Great Expectations', 'website' => 'https://greatexpectations.io', 'description' => 'Data quality and validation platform', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Prefect', 'website' => 'https://prefect.io', 'description' => 'Data workflow orchestration platform', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],
            ['name' => 'Dagster', 'website' => 'https://dagster.io', 'description' => 'Data orchestration platform for ML and analytics', 'category' => 'developer_tools', 'founded_date' => '2018-01-01'],

            // ===== BATCH 2: MORE FINTECH =====
            ['name' => 'Zip Co', 'slug' => 'zip-co', 'website' => 'https://zip.co', 'description' => 'Buy now pay later payments platform', 'category' => 'fintech', 'founded_date' => '2013-01-01'],
            ['name' => 'GoCardless', 'website' => 'https://gocardless.com', 'description' => 'Direct debit and bank payment platform', 'category' => 'fintech', 'founded_date' => '2011-01-01'],
            ['name' => 'Mambu', 'website' => 'https://mambu.com', 'description' => 'Cloud banking platform', 'category' => 'fintech', 'founded_date' => '2011-01-01'],
            ['name' => 'Thought Machine', 'website' => 'https://thoughtmachine.net', 'description' => 'Cloud-native core banking technology', 'category' => 'fintech', 'founded_date' => '2014-01-01'],
            ['name' => 'Rapyd', 'website' => 'https://rapyd.net', 'description' => 'Global fintech-as-a-service platform', 'category' => 'fintech', 'founded_date' => '2016-01-01'],
            ['name' => 'Alloy', 'website' => 'https://alloy.com', 'description' => 'Identity decisioning platform for banks', 'category' => 'fintech', 'founded_date' => '2015-01-01'],
            ['name' => 'Treasury Prime', 'website' => 'https://treasuryprime.com', 'description' => 'Banking-as-a-service API platform', 'category' => 'fintech', 'founded_date' => '2017-01-01'],
            ['name' => 'Column', 'website' => 'https://column.com', 'description' => 'Developer-first bank and financial infrastructure', 'category' => 'fintech', 'founded_date' => '2020-01-01'],
            ['name' => 'Toss', 'website' => 'https://toss.im', 'description' => 'South Korean fintech super app', 'category' => 'fintech', 'founded_date' => '2013-01-01'],
            ['name' => 'Creditas', 'website' => 'https://creditas.com', 'description' => 'Brazilian secured lending platform', 'category' => 'fintech', 'founded_date' => '2012-01-01'],
            ['name' => 'Neon Bank', 'slug' => 'neon-bank', 'website' => 'https://neon.com.br', 'description' => 'Brazilian digital bank', 'category' => 'fintech', 'founded_date' => '2016-01-01'],
            ['name' => 'dLocal', 'website' => 'https://dlocal.com', 'description' => 'Emerging market payment processing', 'category' => 'fintech', 'founded_date' => '2016-01-01'],

            // ===== BATCH 2: MORE CONSUMER =====
            ['name' => 'Depop', 'website' => 'https://depop.com', 'description' => 'Social marketplace for secondhand fashion', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'Oura', 'website' => 'https://ouraring.com', 'description' => 'Smart ring for health and sleep tracking', 'category' => 'consumer', 'founded_date' => '2013-01-01'],
            ['name' => 'Whoop', 'website' => 'https://whoop.com', 'description' => 'Wearable fitness and health performance tracker', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Eight Sleep', 'website' => 'https://eightsleep.com', 'description' => 'Smart mattress and sleep technology', 'category' => 'consumer', 'founded_date' => '2014-01-01'],
            ['name' => 'Tonal', 'website' => 'https://tonal.com', 'description' => 'AI-powered home gym and strength training', 'category' => 'consumer', 'founded_date' => '2015-01-01'],
            ['name' => 'Peloton', 'website' => 'https://onepeloton.com', 'description' => 'Connected fitness equipment and content platform', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'AllTrails', 'website' => 'https://alltrails.com', 'description' => 'Trail discovery and outdoor activity platform', 'category' => 'consumer', 'founded_date' => '2010-01-01'],
            ['name' => 'Strava', 'website' => 'https://strava.com', 'description' => 'Social fitness tracking and athletic community', 'category' => 'consumer', 'founded_date' => '2009-01-01'],
            ['name' => 'Nextdoor', 'website' => 'https://nextdoor.com', 'description' => 'Neighborhood social networking platform', 'category' => 'consumer', 'founded_date' => '2011-01-01'],
            ['name' => 'Bereal', 'website' => 'https://bereal.com', 'description' => 'Authentic photo-sharing social app', 'category' => 'consumer', 'founded_date' => '2019-01-01'],
            ['name' => 'Locket', 'website' => 'https://locket.camera', 'description' => 'Photo sharing widget for close friends', 'category' => 'consumer', 'founded_date' => '2022-01-01'],
            ['name' => 'Rec Room', 'website' => 'https://recroom.com', 'description' => 'Social VR and cross-platform game creation', 'category' => 'consumer', 'founded_date' => '2016-01-01'],
            ['name' => 'Niantic', 'website' => 'https://nianticlabs.com', 'description' => 'AR gaming platform behind Pokemon Go', 'category' => 'consumer', 'founded_date' => '2010-01-01'],
            ['name' => 'Nykaa', 'website' => 'https://nykaa.com', 'description' => 'Indian beauty and fashion e-commerce platform', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Zomato', 'website' => 'https://zomato.com', 'description' => 'Indian food delivery and restaurant discovery platform', 'category' => 'consumer', 'founded_date' => '2008-01-01'],
            ['name' => 'CRED', 'website' => 'https://cred.club', 'description' => 'Indian credit card rewards and payments app', 'category' => 'fintech', 'founded_date' => '2018-01-01'],
            ['name' => 'PhonePe', 'website' => 'https://phonepe.com', 'description' => 'Indian digital payments platform', 'category' => 'fintech', 'founded_date' => '2015-01-01'],
            ['name' => 'Dream11', 'website' => 'https://dream11.com', 'description' => 'Indian fantasy sports platform', 'category' => 'consumer', 'founded_date' => '2008-01-01'],
            ['name' => 'Coursera', 'website' => 'https://coursera.org', 'description' => 'Online learning platform with university courses', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Masterclass', 'website' => 'https://masterclass.com', 'description' => 'Celebrity-taught online classes', 'category' => 'consumer', 'founded_date' => '2015-01-01'],
            ['name' => 'Brilliant', 'website' => 'https://brilliant.org', 'description' => 'STEM learning through interactive problem solving', 'category' => 'consumer', 'founded_date' => '2012-01-01'],
            ['name' => 'Opendoor', 'website' => 'https://opendoor.com', 'description' => 'Digital platform for buying and selling homes', 'category' => 'consumer', 'founded_date' => '2014-01-01'],
            ['name' => 'Back Market', 'website' => 'https://backmarket.com', 'description' => 'Refurbished electronics marketplace', 'category' => 'consumer', 'founded_date' => '2014-01-01'],

            // ===== BATCH 2: MORE HEALTHCARE =====
            ['name' => 'Spring Health', 'website' => 'https://springhealth.com', 'description' => 'Precision mental health platform for employers', 'category' => 'healthcare', 'founded_date' => '2016-01-01'],
            ['name' => 'Lyra Health', 'website' => 'https://lyrahealth.com', 'description' => 'Workforce mental health platform', 'category' => 'healthcare', 'founded_date' => '2015-01-01'],
            ['name' => 'Modern Health', 'website' => 'https://modernhealth.com', 'description' => 'Mental wellness benefits platform', 'category' => 'healthcare', 'founded_date' => '2017-01-01'],
            ['name' => 'Hinge Health', 'website' => 'https://hingehealth.com', 'description' => 'Digital musculoskeletal care platform', 'category' => 'healthcare', 'founded_date' => '2014-01-01'],
            ['name' => 'Omada Health', 'website' => 'https://omadahealth.com', 'description' => 'Virtual chronic condition management', 'category' => 'healthcare', 'founded_date' => '2011-01-01'],
            ['name' => 'Alma', 'website' => 'https://helloalma.com', 'description' => 'Mental health practice management platform', 'category' => 'healthcare', 'founded_date' => '2018-01-01'],
            ['name' => 'Recursion', 'website' => 'https://recursion.com', 'description' => 'AI-powered drug discovery platform', 'category' => 'healthcare', 'founded_date' => '2013-01-01'],
            ['name' => 'Insitro', 'website' => 'https://insitro.com', 'description' => 'Machine learning for drug discovery', 'category' => 'healthcare', 'founded_date' => '2018-01-01'],
            ['name' => 'Alan', 'website' => 'https://alan.com', 'description' => 'European digital health insurance', 'category' => 'healthcare', 'founded_date' => '2016-01-01'],

            // ===== BATCH 2: MORE SECURITY =====
            ['name' => 'Cybereason', 'website' => 'https://cybereason.com', 'description' => 'AI-powered endpoint detection and response', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Netskope', 'website' => 'https://netskope.com', 'description' => 'Cloud security and SASE platform', 'category' => 'enterprise', 'founded_date' => '2012-01-01'],
            ['name' => 'Armis', 'website' => 'https://armis.com', 'description' => 'Asset intelligence and security platform', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Cato Networks', 'website' => 'https://catonetworks.com', 'description' => 'Cloud-native SASE platform', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],
            ['name' => 'Illumio', 'website' => 'https://illumio.com', 'description' => 'Zero trust segmentation for cybersecurity', 'category' => 'enterprise', 'founded_date' => '2013-01-01'],
            ['name' => 'Axonius', 'website' => 'https://axonius.com', 'description' => 'Cyber asset attack surface management', 'category' => 'enterprise', 'founded_date' => '2017-01-01'],
            ['name' => 'Semgrep', 'website' => 'https://semgrep.dev', 'description' => 'Static analysis and code security platform', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'Chainguard', 'website' => 'https://chainguard.dev', 'description' => 'Secure container images and software supply chain', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],

            // ===== BATCH 2: CRYPTO/WEB3 =====
            ['name' => 'Alchemy', 'website' => 'https://alchemy.com', 'description' => 'Web3 development platform and node infrastructure', 'category' => 'developer_tools', 'founded_date' => '2017-01-01'],
            ['name' => 'Phantom', 'website' => 'https://phantom.app', 'description' => 'Multi-chain crypto wallet', 'category' => 'fintech', 'founded_date' => '2021-01-01'],
            ['name' => 'Magic Eden', 'website' => 'https://magiceden.io', 'description' => 'Multi-chain NFT marketplace', 'category' => 'consumer', 'founded_date' => '2021-01-01'],
            ['name' => 'LayerZero', 'website' => 'https://layerzero.network', 'description' => 'Omnichain interoperability protocol', 'category' => 'developer_tools', 'founded_date' => '2021-01-01'],
            ['name' => 'Aptos', 'website' => 'https://aptoslabs.com', 'description' => 'Layer 1 blockchain for mainstream adoption', 'category' => 'developer_tools', 'founded_date' => '2022-01-01'],
            ['name' => 'Celestia', 'website' => 'https://celestia.org', 'description' => 'Modular data availability network', 'category' => 'developer_tools', 'founded_date' => '2019-01-01'],
            ['name' => 'Worldcoin', 'website' => 'https://worldcoin.org', 'description' => 'Global identity and financial network', 'category' => 'fintech', 'founded_date' => '2019-01-01'],
            ['name' => 'Circle', 'website' => 'https://circle.com', 'description' => 'USDC stablecoin and digital currency infrastructure', 'category' => 'fintech', 'founded_date' => '2013-01-01'],

            // ===== BATCH 2: INFRA =====
            ['name' => 'Fastly', 'website' => 'https://fastly.com', 'description' => 'Edge cloud platform and CDN', 'category' => 'developer_tools', 'founded_date' => '2011-01-01'],
            ['name' => 'Vultr', 'website' => 'https://vultr.com', 'description' => 'Cloud computing and infrastructure', 'category' => 'developer_tools', 'founded_date' => '2014-01-01'],
            ['name' => 'DigitalOcean', 'website' => 'https://digitalocean.com', 'description' => 'Cloud infrastructure for developers', 'category' => 'developer_tools', 'founded_date' => '2011-01-01'],

            // ===== BATCH 3: EUROPEAN/MISC =====
            ['name' => 'Bolt Financial', 'website' => 'https://bolt.com', 'description' => 'One-click checkout platform', 'category' => 'fintech', 'founded_date' => '2014-01-01'],
            ['name' => 'Wefox', 'website' => 'https://wefox.com', 'description' => 'European insurtech platform', 'category' => 'fintech', 'founded_date' => '2015-01-01'],
            ['name' => 'Personio', 'website' => 'https://personio.com', 'description' => 'European HR management platform', 'category' => 'enterprise', 'founded_date' => '2015-01-01'],

            // ===== BATCH 2: DEFENSE =====
            ['name' => 'Hadrian', 'website' => 'https://hadrian.co', 'description' => 'Automated precision manufacturing for aerospace', 'category' => 'defense', 'founded_date' => '2020-01-01'],
            ['name' => 'Epirus', 'website' => 'https://epirusinc.com', 'description' => 'Directed energy and power management for defense', 'category' => 'defense', 'founded_date' => '2018-01-01'],
            ['name' => 'Saronic', 'website' => 'https://saronic.com', 'description' => 'Autonomous surface vessels for naval defense', 'category' => 'defense', 'founded_date' => '2022-01-01'],
            ['name' => 'Hermeus', 'website' => 'https://hermeus.com', 'description' => 'Hypersonic aircraft development', 'category' => 'defense', 'founded_date' => '2018-01-01'],

            // ===== BATCH 2: SPACE =====
            ['name' => 'Rocket Lab', 'website' => 'https://rocketlabusa.com', 'description' => 'Small satellite launch services', 'category' => 'space', 'founded_date' => '2006-01-01'],
            ['name' => 'Planet Labs', 'website' => 'https://planet.com', 'description' => 'Earth observation satellite imagery', 'category' => 'space', 'founded_date' => '2010-01-01'],
            ['name' => 'Astra', 'website' => 'https://astra.com', 'description' => 'Small rocket launch services', 'category' => 'space', 'founded_date' => '2016-01-01'],

            // ===== BATCH 2: CLIMATE =====
            ['name' => 'Form Energy', 'website' => 'https://formenergy.com', 'description' => 'Long-duration energy storage using iron-air batteries', 'category' => 'climate', 'founded_date' => '2017-01-01'],
            ['name' => 'Commonwealth Fusion Systems', 'website' => 'https://cfs.energy', 'description' => 'Fusion energy technology development', 'category' => 'climate', 'founded_date' => '2018-01-01'],
            ['name' => 'Helion Energy', 'website' => 'https://helionenergy.com', 'description' => 'Fusion power company', 'category' => 'climate', 'founded_date' => '2013-01-01'],
            ['name' => 'Northvolt', 'website' => 'https://northvolt.com', 'description' => 'European battery cell manufacturer', 'category' => 'climate', 'founded_date' => '2016-01-01'],
            ['name' => 'Climeworks', 'website' => 'https://climeworks.com', 'description' => 'Direct air carbon capture and storage', 'category' => 'climate', 'founded_date' => '2009-01-01'],
            ['name' => 'Pachama', 'website' => 'https://pachama.com', 'description' => 'AI-verified carbon credits from forest projects', 'category' => 'climate', 'founded_date' => '2018-01-01'],
            ['name' => 'Lucid Motors', 'website' => 'https://lucidmotors.com', 'description' => 'Luxury electric vehicle manufacturer', 'category' => 'climate', 'founded_date' => '2007-01-01'],
        ];
    }
}
