<?php

namespace Database\Seeders;

use App\Models\Company;
use Illuminate\Database\Seeder;

class ProductHighlightsSeeder extends Seeder
{
    public function run(): void
    {
        $highlights = [
            'spacex' => [
                'Falcon 9 reusable rocket with 134 launches in 2024',
                'Falcon Heavy for heavy-lift missions',
                'Starship next-gen spacecraft for Mars missions',
                'Starlink satellite internet with 6,850+ active satellites',
                'Dragon spacecraft for crew and cargo to ISS',
                'First private spacewalk achieved with Polaris Dawn mission',
            ],
            'bytedance' => [
                'TikTok short-form video platform with 1B+ users',
                'Douyin Chinese version with $483B e-commerce GMV',
                'CapCut video editing app with 200M+ monthly users',
                'Lark enterprise collaboration platform (chat, video, docs)',
                'Toutiao AI-powered news aggregator',
                'Pico VR headsets and devices',
            ],
            'revolut' => [
                'Digital banking app supporting 120+ currencies',
                'Revolut X crypto exchange for advanced traders',
                'Stock and crypto trading with fractional shares',
                'International money transfers at interbank rates',
                'Business accounts with expense management',
                'UK banking license granted September 2024',
            ],
            'klarna' => [
                'Pay in 4 interest-free installments',
                'Pay in 30 days deferred payment',
                'Monthly financing up to 24 months',
                'Klarna Card for flexible payments anywhere',
                'Shopping browser extension with price comparisons',
                'AI-powered shopping assistant',
            ],
            'airbnb' => [
                'Vacation rental marketplace in 220+ countries',
                'Airbnb Experiences for local activities and tours',
                'Icons extraordinary experiences with celebrities',
                'Co-Host Network for property management',
                'Airbnb Services for chefs, trainers, massages',
                'Group trip planning with shared wishlists',
            ],
            'dropbox' => [
                'Cloud file storage and synchronization',
                'Dropbox Paper collaborative documents',
                'Dropbox Sign (formerly HelloSign) e-signatures',
                'Dropbox Backup automatic computer backup',
                'Smart Sync for selective file syncing',
                'Dropbox Dash AI-powered universal search',
            ],
            'doordash' => [
                'On-demand food delivery from restaurants',
                'DashPass subscription for free delivery',
                'Grocery and convenience store delivery',
                'Alcohol delivery in select markets',
                'DoorDash for Business corporate ordering',
                'DoorDash Drive white-label delivery API',
            ],
            'coinbase' => [
                'Cryptocurrency exchange with 200+ assets',
                'Coinbase Wallet self-custody crypto wallet',
                'Staking services for ETH, SOL, and more',
                'Coinbase Prime institutional trading',
                'Base L2 Ethereum blockchain',
                'Coinbase One premium membership',
            ],
            'instacart' => [
                'Same-day grocery delivery from local stores',
                'Instacart+ membership for unlimited free delivery',
                'Curbside pickup from partner stores',
                'Instacart Ads platform for CPG brands',
                'Carrot AI for personalized recommendations',
                'Enterprise solutions for retailers',
            ],
            'reddit' => [
                'Community-driven discussion platform',
                '100,000+ active subreddits',
                'Reddit Premium ad-free experience',
                'Reddit Coins and Awards system',
                'Reddit Talk audio conversations',
                'Developer Platform for apps and bots',
            ],
            'gitlab' => [
                'Complete DevSecOps platform in one application',
                'Built-in CI/CD pipelines with Auto DevOps',
                'Source code management with merge requests',
                'Security scanning (SAST, DAST, dependency)',
                'Container Registry for Docker images',
                'GitLab Duo AI-powered coding assistant',
            ],
            'zapier' => [
                'No-code automation connecting 6,000+ apps',
                'Zaps automated workflows triggered by events',
                'Multi-step Zaps with conditional logic',
                'Zapier Tables lightweight database',
                'Zapier Interfaces custom forms and pages',
                'Zapier Canvas visual workflow builder',
            ],
            'gusto' => [
                'Full-service payroll processing',
                'Employee benefits administration',
                'HR management and onboarding',
                'Time tracking and PTO management',
                'Workers comp and compliance',
                'Embedded payroll API for platforms',
            ],
            'deel' => [
                'Global payroll in 150+ countries',
                'EOR (Employer of Record) services',
                'Contractor management and payments',
                'Visa and immigration support',
                'Deel HR for workforce management',
                'Compliance and tax handling',
            ],
            'plaid' => [
                'Financial data connectivity platform',
                'Bank account verification',
                'Identity verification and KYC',
                'Income and employment verification',
                'Transaction data enrichment',
                'Payments initiation (ACH, RTP)',
            ],
            'ramp' => [
                'Corporate cards with 1.5% cashback',
                'Expense management and tracking',
                'Bill pay and vendor management',
                'Accounting integrations (QuickBooks, NetSuite)',
                'Ramp Intelligence AI spend insights',
                'Travel booking and management',
            ],
            'brex' => [
                'Corporate cards for startups and enterprises',
                'Brex Empower spend management platform',
                'Bill pay and reimbursements',
                'Business accounts with high yield',
                'Travel and expense management',
                'Startup-focused credit underwriting',
            ],
            'scale-ai' => [
                'Data labeling for machine learning',
                'Scale Generative AI Platform',
                'Scale Donovan for government/defense AI',
                'Evaluation and fine-tuning services',
                'Synthetic data generation',
                'RLHF (Reinforcement Learning from Human Feedback)',
            ],
            'datadog' => [
                'Infrastructure monitoring and APM',
                'Log management and analytics',
                'Real user monitoring (RUM)',
                'Synthetic monitoring and testing',
                'Security monitoring (SIEM)',
                'CI/CD visibility and testing',
            ],
            'vercel' => [
                'Frontend cloud platform for web deployment',
                'Next.js framework development',
                'Edge Functions for serverless compute',
                'Vercel AI SDK for building AI apps',
                'Preview deployments for every git push',
                'Analytics and speed insights',
            ],
            'retool' => [
                'Low-code internal tools builder',
                'Drag-and-drop UI components',
                'Database and API integrations',
                'Retool Mobile for native apps',
                'Retool Workflows automation',
                'Self-hosted and cloud options',
            ],
            'linear' => [
                'Issue tracking for software teams',
                'Project and cycle management',
                'Roadmap planning and visualization',
                'Git and Slack integrations',
                'Linear Asks for intake management',
                'AI-powered issue triage and writing',
            ],
            'airtable' => [
                'Spreadsheet-database hybrid platform',
                'Custom views (grid, calendar, kanban, gallery)',
                'Automations and integrations',
                'Interface Designer for apps',
                'AI-powered formula generation',
                'Enterprise-grade security and admin',
            ],
            'asana' => [
                'Work management and project tracking',
                'Portfolio management for initiatives',
                'Timeline (Gantt) and board views',
                'Goals and OKR tracking',
                'Workflow Builder automation',
                'Asana Intelligence AI features',
            ],
            'mondaycom' => [
                'Work OS for team collaboration',
                'Project and portfolio management',
                'CRM and sales pipeline',
                'Marketing campaign management',
                'Software development workflows',
                'Custom apps and integrations',
            ],
            'clickup' => [
                'All-in-one productivity platform',
                'Tasks, docs, goals, and time tracking',
                'Whiteboards for collaboration',
                'ClickUp Brain AI assistant',
                'Custom views and dashboards',
                'Automation and integrations',
            ],
            'miro' => [
                'Online collaborative whiteboard',
                'Templates for workshops and planning',
                'Diagramming and flowcharts',
                'Video chat and screen sharing',
                'Miro AI for content generation',
                'Enterprise security and admin',
            ],
            'webflow' => [
                'Visual website builder without code',
                'CMS for dynamic content',
                'E-commerce capabilities',
                'Hosting with global CDN',
                'Interactions and animations',
                'Webflow Apps marketplace',
            ],
            'supabase' => [
                'Open source Firebase alternative',
                'Postgres database with real-time subscriptions',
                'Authentication and authorization',
                'Edge Functions serverless compute',
                'Storage for files and media',
                'Vector embeddings for AI apps',
            ],
            'perplexity' => [
                'AI-powered answer engine with citations',
                'Real-time web search integration',
                'Pro Search for complex research',
                'Perplexity Pages for publishing',
                'API for developers',
                'Enterprise search solutions',
            ],
            'characterai' => [
                'AI chatbots with distinct personalities',
                'Character creation and customization',
                'Group chats with multiple AI characters',
                'Voice conversations with AI',
                'Character personas for entertainment and roleplay',
                'Mobile apps for iOS and Android',
            ],
            'cohere' => [
                'Enterprise LLMs (Command, Embed, Rerank)',
                'Retrieval Augmented Generation (RAG)',
                'Multi-language support in 100+ languages',
                'Cohere Toolkit open-source deployment',
                'Fine-tuning for custom models',
                'Data privacy with deployment flexibility',
            ],
            'hugging-face' => [
                'Hub hosting 500K+ ML models',
                'Transformers library for NLP',
                'Datasets library with 100K+ datasets',
                'Spaces for ML app hosting',
                'Inference API for model deployment',
                'Enterprise Hub for organizations',
            ],
            'mistral-ai' => [
                'Open-weight foundation models (Mistral, Mixtral)',
                'Le Chat consumer AI assistant',
                'La Plateforme API for developers',
                'Codestral code generation model',
                'Multi-language and reasoning capabilities',
                'European AI sovereignty focus',
            ],
            'replit' => [
                'Browser-based IDE and coding environment',
                'Replit Agent AI pair programmer',
                'Instant deployment and hosting',
                'Multiplayer collaborative coding',
                'Ghostwriter AI code completion',
                'Learn to code tutorials',
            ],
            'cursor' => [
                'AI-first code editor built on VS Code',
                'AI chat for codebase Q&A',
                'AI-powered code completion',
                'Multi-file editing with AI',
                'Codebase understanding and context',
                'Privacy mode for sensitive code',
            ],
            'checkoutcom' => [
                'Enterprise payment processing platform',
                'Support for 150+ currencies',
                'Fraud detection with machine learning',
                'Unified payments API',
                'Issuing and card services',
                'Real-time payment analytics',
            ],
            'twitch' => [
                'Live streaming platform for gaming',
                'Creator monetization (subscriptions, bits)',
                'Twitch Prime gaming benefits',
                'Interactive chat and emotes',
                'Esports and event broadcasting',
                'Clips and VOD storage',
            ],
            'cruise' => [
                'Autonomous vehicle technology',
                'Self-driving robotaxi service',
                'Purpose-built Origin vehicle',
                'Urban mobility focus',
                'GM partnership for manufacturing',
                'AI and sensor fusion systems',
            ],
            'pagerduty' => [
                'Incident management platform',
                'On-call scheduling and escalations',
                'AIOps for noise reduction',
                'Status pages and communication',
                'Automation and runbooks',
                'Integration with 700+ tools',
            ],
            'whatnot' => [
                'Live shopping and auction platform',
                'Categories: collectibles, cards, fashion',
                'Real-time bidding experience',
                'Seller tools and analytics',
                'Authentication services',
                'Community-driven marketplace',
            ],
            'benchling' => [
                'R&D cloud for life sciences',
                'Molecular biology design tools',
                'Lab notebook (ELN)',
                'LIMS and inventory management',
                'Insights and analytics',
                'Regulatory compliance support',
            ],
            'ginkgo-bioworks' => [
                'Cell programming and biosecurity platform',
                'Organism engineering for biotech',
                'Foundry services for customers',
                'Codebase of genetic parts',
                'Biosecurity monitoring',
                'Partnerships across industries',
            ],
            'amplitude' => [
                'Product analytics platform',
                'User behavior tracking',
                'Cohort analysis and funnels',
                'A/B testing and experimentation',
                'Session replay',
                'Customer data platform (CDP)',
            ],
            'xai' => [
                'Grok AI assistant (integrated with X)',
                'Real-time information access',
                'Colossus AI training supercomputer',
                'Focus on understanding the universe',
                'Grok-2 multimodal capabilities',
                'Image generation features',
            ],
            'groq' => [
                'LPU (Language Processing Unit) inference chips',
                'Fastest LLM inference in the world',
                'GroqCloud API for developers',
                'Open model hosting (Llama, Mixtral)',
                'Low latency for real-time AI',
                'Custom silicon architecture',
            ],
            'cerebras-systems' => [
                'Wafer-scale AI chips (WSE)',
                'CS-2 AI training system',
                'Cerebras Cloud for model training',
                'Andromeda AI supercomputer',
                'GPT and LLM training at scale',
                'Memory-bandwidth optimized design',
            ],
            'stability-ai' => [
                'Stable Diffusion image generation',
                'Stable Video for video generation',
                'Stable Audio for music/sound',
                'Stable LM language models',
                'Open-source model releases',
                'API and enterprise solutions',
            ],
            'midjourney' => [
                'AI image generation via Discord',
                'Photorealistic and artistic styles',
                'Prompt-based creation',
                'Community showcase and curation',
                'Subscription tiers for usage',
                'Web interface (alpha)',
            ],
            'runway' => [
                'Gen-3 video generation AI',
                'AI video editing tools',
                'Green Screen and inpainting',
                'Motion brush for animation',
                'API for developers',
                'Used in film and TV production',
            ],
            'synthesia' => [
                'AI video generation with avatars',
                'Text-to-video in 120+ languages',
                'Custom AI avatar creation',
                'Enterprise video platform',
                'Training and onboarding videos',
                'Integration with learning platforms',
            ],
            'harvey' => [
                'AI assistant for legal professionals',
                'Contract analysis and drafting',
                'Legal research assistance',
                'Due diligence automation',
                'Trained on legal data',
                'Enterprise security and compliance',
            ],
            'anyscale' => [
                'Ray distributed computing platform',
                'Serverless AI infrastructure',
                'LLM training and fine-tuning',
                'Model serving at scale',
                'Open-source Ray framework',
                'Enterprise support and hosting',
            ],
            'inflection-ai' => [
                'Pi personal AI assistant',
                'Conversational AI focus',
                'Emotional intelligence in AI',
                'Inflection-2 foundation model',
                'Consumer-friendly interface',
                'Privacy-focused design',
            ],
            'together-ai' => [
                'Open model cloud platform',
                'Fine-tuning and training services',
                'Inference API for open models',
                'GPU clusters for AI workloads',
                'Together Inference Engine',
                'Research collaborations',
            ],
            'adept' => [
                'AI agents for knowledge work',
                'ACT-1 action transformer model',
                'Browser and software automation',
                'Enterprise workflow agents',
                'Natural language to actions',
                'Cross-application capabilities',
            ],
            'jasper' => [
                'AI marketing content platform',
                'Brand voice customization',
                'Campaign and content generation',
                'AI image creation',
                'Marketing workflow automation',
                'Enterprise brand management',
            ],
            'copyai' => [
                'AI copywriting and content generation',
                'Marketing copy templates',
                'Blog and social media content',
                'Sales outreach automation',
                'Workflows for content teams',
                '95+ languages supported',
            ],
            'glean' => [
                'Enterprise AI search platform',
                'Unified search across work apps',
                'Knowledge management',
                'AI assistant for employees',
                'Personalized results',
                'Security and permissions',
            ],
            'writer' => [
                'Enterprise generative AI platform',
                'Brand-consistent content generation',
                'Palmyra LLM family',
                'AI guardrails and compliance',
                'Knowledge Graph integration',
                'Style guide enforcement',
            ],
            'weights-biases' => [
                'MLOps platform for AI teams',
                'Experiment tracking and visualization',
                'Model versioning and registry',
                'Hyperparameter sweeps',
                'Dataset versioning',
                'Collaboration and reporting',
            ],
            'mosaic-ml' => [
                'MPT foundation models',
                'LLM training platform',
                'Custom model development',
                'Inference optimization',
                'Now part of Databricks',
                'Open-source model releases',
            ],
            'chime' => [
                'Mobile-first banking app',
                'No monthly fees or minimums',
                'Early direct deposit',
                'SpotMe overdraft protection',
                'High-yield savings account',
                'Credit Builder secured card',
            ],
            'mercury' => [
                'Banking for startups',
                'Checking and savings accounts',
                'Treasury management',
                'Corporate cards',
                'Venture debt',
                'Financial workflows and APIs',
            ],
            'navan' => [
                'Business travel and expense platform',
                'Corporate travel booking',
                'Expense management',
                'Travel policy compliance',
                'Virtual and physical cards',
                'Real-time spend visibility',
            ],
            'marqeta' => [
                'Modern card issuing platform',
                'API-first card creation',
                'Real-time transaction controls',
                'Tokenization services',
                'Buy now pay later enablement',
                'Used by Square, DoorDash, Instacart',
            ],
            'affirm' => [
                'Buy now pay later financing',
                'Pay-in-4 interest-free option',
                'Monthly payment plans',
                'Affirm Card for flexible payments',
                'Merchant integrations',
                'No hidden fees transparency',
            ],
            'robinhood' => [
                'Commission-free stock trading',
                'Options and crypto trading',
                'Robinhood Gold margin accounts',
                'Cash management with interest',
                'Retirement accounts (IRAs)',
                '24-hour market trading',
            ],
            'wise' => [
                'International money transfers',
                'Multi-currency account',
                'Wise Business for companies',
                'Debit card in 40+ currencies',
                'Mid-market exchange rates',
                'Platform API for businesses',
            ],
            'postman' => [
                'API development platform',
                'API testing and documentation',
                'Collaboration workspaces',
                'Mock servers for development',
                'API monitoring',
                'Public API Network',
            ],
            'snyk' => [
                'Developer security platform',
                'Open source vulnerability scanning',
                'Container security',
                'Infrastructure as code scanning',
                'Code security analysis',
                'License compliance',
            ],
            'hashicorp' => [
                'Terraform infrastructure as code',
                'Vault secrets management',
                'Consul service mesh',
                'Nomad workload orchestration',
                'HCP cloud platform',
                'Enterprise security and governance',
            ],
            'grafana-labs' => [
                'Grafana visualization and dashboards',
                'Loki log aggregation',
                'Tempo distributed tracing',
                'Mimir metrics at scale',
                'Grafana Cloud managed platform',
                'Open-source observability stack',
            ],
            'launchdarkly' => [
                'Feature flag management platform',
                'Progressive rollouts and targeting',
                'Experimentation and A/B testing',
                'Feature workflows and approvals',
                'SDKs for all major languages',
                'Enterprise governance',
            ],
            'devoted-health' => [
                'Medicare Advantage health plans',
                'Personalized care guides',
                'In-home care services',
                'Technology-enabled care',
                'Prescription drug coverage',
                'Focus on senior health',
            ],
            'ro' => [
                'Digital health clinic',
                'Telehealth consultations',
                'Prescription delivery',
                'Roman (mens health)',
                'Rory (womens health)',
                'Plenity weight management',
            ],
            'hims-hers' => [
                'Telehealth and wellness platform',
                'Hims for mens health',
                'Hers for womens health',
                'Prescription treatments delivered',
                'Mental health services',
                'Skincare and haircare products',
            ],
            'tempus' => [
                'AI-powered precision medicine',
                'Genomic sequencing and testing',
                'Clinical data analysis',
                'Oncology-focused insights',
                'Drug discovery partnerships',
                'Real-world evidence platform',
            ],
            'noom' => [
                'Psychology-based weight loss app',
                'Personalized coaching',
                'Food logging and tracking',
                'Behavior change curriculum',
                'Noom Med for clinical weight loss',
                'Mental health support',
            ],
            'calm' => [
                'Meditation and sleep app',
                'Guided meditation sessions',
                'Sleep Stories narrated content',
                'Music for focus and relaxation',
                'Calm Business for employers',
                'Calm Health clinical programs',
            ],
            'headspace' => [
                'Meditation and mindfulness app',
                'Guided meditations library',
                'Sleep content and sounds',
                'Focus and movement exercises',
                'Headspace for Work',
                'Mental health partnerships',
            ],
            'faire' => [
                'Wholesale marketplace for retailers',
                'Net 60 payment terms',
                'Free returns on first orders',
                'Independent brands and makers',
                'Retailer discovery tools',
                'Data-driven recommendations',
            ],
            'flexport' => [
                'Digital freight forwarding',
                'End-to-end supply chain platform',
                'Ocean, air, and trucking logistics',
                'Customs and trade compliance',
                'Real-time shipment visibility',
                'Trade finance services',
            ],
            'fanatics' => [
                'Licensed sports merchandise',
                'Official leagues partnerships (NFL, MLB, NBA)',
                'Fanatics Collectibles trading cards',
                'Sports betting (Fanatics Sportsbook)',
                'Direct-to-consumer e-commerce',
                'On-demand manufacturing',
            ],
            'stockx' => [
                'Sneaker and streetwear marketplace',
                'Authentication for all products',
                'Bid/ask stock market model',
                'Collectibles and electronics',
                'Real-time pricing data',
                'Global shipping and verification',
            ],
            'goat' => [
                'Sneaker marketplace with authentication',
                'New and used sneakers',
                'Apparel and accessories',
                'Flight Club retail integration',
                'Global buyer/seller network',
                'Instant ship and consignment',
            ],
            'poshmark' => [
                'Social commerce fashion marketplace',
                'Peer-to-peer selling',
                'Posh Parties live shopping',
                'Authentication for luxury',
                'Poshmark Closet tools',
                'Community-driven discovery',
            ],
            'shipt' => [
                'Same-day delivery service',
                'Grocery and household items',
                'Shipt membership program',
                'Target partnership',
                'Personal shoppers network',
                'Retailer delivery solutions',
            ],
            'waymo' => [
                'Autonomous driving technology',
                'Waymo One robotaxi service',
                'Waymo Via trucking',
                'Waymo Driver AI system',
                'Operations in Phoenix and San Francisco',
                'Partnership with Uber',
            ],
            'rivian' => [
                'Electric adventure vehicles',
                'R1T electric pickup truck',
                'R1S electric SUV',
                'Amazon delivery van fleet',
                'Rivian Adventure Network charging',
                'Direct-to-consumer sales',
            ],
            'aurora' => [
                'Aurora Driver autonomous system',
                'Self-driving trucking focus',
                'Hardware and software stack',
                'Aurora Horizon trucking service',
                'Partnerships with Volvo and PACCAR',
                'Simulation and testing platform',
            ],
            'nuro' => [
                'Autonomous delivery vehicles',
                'Purpose-built delivery bots',
                'Last-mile delivery focus',
                'Partnerships with grocers and retailers',
                'Zero-occupant vehicle design',
                'Nuro Driver AI system',
            ],
            'bird' => [
                'Electric scooter sharing',
                'Micromobility platform',
                'Bird Three scooter model',
                'City partnerships',
                'Fleet management software',
                'Sustainable urban transport',
            ],
            'servicetitan' => [
                'Software for home service businesses',
                'Dispatching and scheduling',
                'Customer management',
                'Invoicing and payments',
                'Marketing automation',
                'Reporting and analytics',
            ],
            'toast' => [
                'Restaurant management platform',
                'POS system for restaurants',
                'Online ordering and delivery',
                'Payroll and team management',
                'Marketing and loyalty',
                'Payment processing',
            ],
            'celonis' => [
                'Process mining and intelligence',
                'Execution management system',
                'Process analytics and insights',
                'Action flows automation',
                'ERP system integration',
                'Enterprise transformation',
            ],
            'uipath' => [
                'Robotic process automation (RPA)',
                'UiPath Studio for bot building',
                'AI-powered automation',
                'Document understanding',
                'Process mining',
                'Attended and unattended bots',
            ],
            'loom' => [
                'Async video messaging',
                'Screen and camera recording',
                'Video editing and trimming',
                'Viewer insights and analytics',
                'Team video library',
                'Now part of Atlassian',
            ],
            'calendly' => [
                'Scheduling automation platform',
                'Meeting booking links',
                'Team scheduling pages',
                'Calendar integrations',
                'Workflow automations',
                'Routing and round-robin',
            ],
        ];

        foreach ($highlights as $slug => $productHighlights) {
            $company = Company::where('slug', $slug)->first();
            if ($company && !$company->product_highlights) {
                $company->update([
                    'product_highlights' => $productHighlights,
                    'profile_refreshed_at' => now(),
                ]);
            }
        }

        $this->command->info('Updated ' . count($highlights) . ' companies with product highlights.');
    }
}
