<?php

namespace Database\Seeders;

use App\Models\Company;
use Illuminate\Database\Seeder;

class TechCrunchCompaniesSeeder extends Seeder
{
    /**
     * Companies sourced from TechCrunch headlines (Dec 2025 - Jan 2026).
     * Excludes companies already in the database.
     *
     * IMPORTANT: When adding new companies, always include the 'category' field.
     * Valid categories: ai_ml, fintech, enterprise, healthcare, robotics, space, climate, consumer, developer_tools, defense
     */
    public function run(): void
    {
        $companies = [
            // AI/ML Companies
            [
                'name' => 'Applied Intuition',
                'category' => 'ai_ml',
                'slug' => 'applied-intuition',
                'website' => 'https://www.appliedintuition.com',
                'linkedin_url' => 'https://www.linkedin.com/company/applied-intuition',
                'description' => 'AI-powered software for autonomous vehicle development and simulation.',
                'city' => 'Mountain View',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2017-01-01',
            ],
            [
                'name' => 'Figure AI',
                'slug' => 'figure-ai',
                'website' => 'https://www.figure.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/figureai',
                'description' => 'Developing general-purpose humanoid robots powered by AI.',
                'city' => 'Sunnyvale',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2022-01-01',
            ],
            [
                'name' => 'ElevenLabs',
                'slug' => 'elevenlabs',
                'website' => 'https://elevenlabs.io',
                'linkedin_url' => 'https://www.linkedin.com/company/elevenlabsio',
                'description' => 'AI voice technology for realistic text-to-speech and voice cloning.',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'founded_date' => '2022-01-01',
            ],
            [
                'name' => 'Mercor',
                'slug' => 'mercor',
                'website' => 'https://www.mercor.com',
                'linkedin_url' => 'https://www.linkedin.com/company/mercor-ai',
                'description' => 'AI-powered recruiting platform for matching talent with opportunities.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2023-01-01',
            ],
            [
                'name' => 'Lovable',
                'slug' => 'lovable',
                'website' => 'https://lovable.dev',
                'linkedin_url' => 'https://www.linkedin.com/company/lovable-dev',
                'description' => 'AI-powered code generation platform for building web applications.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2023-01-01',
            ],

            // Enterprise/Security
            [
                'name' => 'Island',
                'slug' => 'island',
                'website' => 'https://www.island.io',
                'linkedin_url' => 'https://www.linkedin.com/company/islandio',
                'description' => 'Enterprise browser with built-in security, management, and governance.',
                'city' => 'Dallas',
                'state' => 'TX',
                'country' => 'USA',
                'founded_date' => '2020-01-01',
            ],
            [
                'name' => 'SecurityPal',
                'slug' => 'securitypal',
                'website' => 'https://www.securitypal.co',
                'linkedin_url' => 'https://www.linkedin.com/company/securitypal',
                'description' => 'Platform for automating security questionnaires and compliance.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2021-01-01',
            ],

            // Fintech
            [
                'name' => 'Pine Labs',
                'slug' => 'pine-labs',
                'website' => 'https://www.pinelabs.com',
                'linkedin_url' => 'https://www.linkedin.com/company/pine-labs',
                'description' => 'Merchant commerce platform providing payments and financing solutions.',
                'city' => 'Noida',
                'state' => 'Uttar Pradesh',
                'country' => 'India',
                'founded_date' => '1998-01-01',
            ],
            [
                'name' => 'Karat Financial',
                'slug' => 'karat-financial',
                'website' => 'https://www.trykarat.com',
                'linkedin_url' => 'https://www.linkedin.com/company/karat-financial',
                'description' => 'Business credit cards designed for content creators and influencers.',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2019-01-01',
            ],
            [
                'name' => 'Zip',
                'slug' => 'zip',
                'website' => 'https://zip.co',
                'linkedin_url' => 'https://www.linkedin.com/company/zip-co',
                'description' => 'Buy now, pay later platform for consumer and business payments.',
                'city' => 'Sydney',
                'state' => 'NSW',
                'country' => 'Australia',
                'founded_date' => '2013-01-01',
            ],
            [
                'name' => 'Alpaca',
                'slug' => 'alpaca',
                'website' => 'https://alpaca.markets',
                'linkedin_url' => 'https://www.linkedin.com/company/alpacamarkets',
                'description' => 'API-first stock and crypto brokerage platform for developers.',
                'city' => 'San Mateo',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2015-01-01',
            ],
            [
                'name' => 'Synctera',
                'slug' => 'synctera',
                'website' => 'https://www.synctera.com',
                'linkedin_url' => 'https://www.linkedin.com/company/synctera',
                'description' => 'Banking-as-a-service platform connecting fintechs with banks.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2020-01-01',
            ],
            [
                'name' => 'Djamo',
                'slug' => 'djamo',
                'website' => 'https://www.djamo.com',
                'linkedin_url' => 'https://www.linkedin.com/company/djamo',
                'description' => 'Mobile banking and payments app for French-speaking Africa.',
                'city' => 'Abidjan',
                'state' => null,
                'country' => 'Ivory Coast',
                'founded_date' => '2020-01-01',
            ],

            // Robotics
            [
                'name' => '1X Technologies',
                'slug' => '1x-technologies',
                'website' => 'https://www.1x.tech',
                'linkedin_url' => 'https://www.linkedin.com/company/1x-technologies',
                'description' => 'Building humanoid robots designed for home environments.',
                'city' => 'Palo Alto',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2014-01-01',
            ],
            [
                'name' => 'Pickle Robot',
                'slug' => 'pickle-robot',
                'website' => 'https://www.picklerobot.com',
                'linkedin_url' => 'https://www.linkedin.com/company/pickle-robot',
                'description' => 'Robotic systems for automating warehouse truck unloading.',
                'city' => 'Cambridge',
                'state' => 'MA',
                'country' => 'USA',
                'founded_date' => '2018-01-01',
            ],
            [
                'name' => 'Coco',
                'slug' => 'coco',
                'website' => 'https://www.cocodelivery.com',
                'linkedin_url' => 'https://www.linkedin.com/company/cocodelivery',
                'description' => 'Sidewalk delivery robots for restaurants and retailers.',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2020-01-01',
            ],
            [
                'name' => 'Diligent Robotics',
                'slug' => 'diligent-robotics',
                'website' => 'https://www.diligentrobots.com',
                'linkedin_url' => 'https://www.linkedin.com/company/diligent-robotics',
                'description' => 'Hospital robots that assist nurses with routine tasks.',
                'city' => 'Austin',
                'state' => 'TX',
                'country' => 'USA',
                'founded_date' => '2017-01-01',
            ],
            [
                'name' => 'Chef Robotics',
                'slug' => 'chef-robotics',
                'website' => 'https://www.chefrobotics.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/chef-robotics',
                'description' => 'AI-powered robotic systems for food assembly and production.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2019-01-01',
            ],
            [
                'name' => 'Apptronik',
                'slug' => 'apptronik',
                'website' => 'https://apptronik.com',
                'linkedin_url' => 'https://www.linkedin.com/company/apptronik',
                'description' => 'Building general-purpose humanoid robots for commercial applications.',
                'city' => 'Austin',
                'state' => 'TX',
                'country' => 'USA',
                'founded_date' => '2016-01-01',
            ],
            [
                'name' => 'Agility Robotics',
                'slug' => 'agility-robotics',
                'website' => 'https://agilityrobotics.com',
                'linkedin_url' => 'https://www.linkedin.com/company/agility-robotics',
                'description' => 'Creator of Digit, a bipedal robot designed for logistics work.',
                'city' => 'Corvallis',
                'state' => 'OR',
                'country' => 'USA',
                'founded_date' => '2015-01-01',
            ],

            // Space
            [
                'name' => 'Blue Origin',
                'slug' => 'blue-origin',
                'website' => 'https://www.blueorigin.com',
                'linkedin_url' => 'https://www.linkedin.com/company/blue-origin',
                'description' => 'Aerospace manufacturer developing reusable rockets and spacecraft.',
                'city' => 'Kent',
                'state' => 'WA',
                'country' => 'USA',
                'founded_date' => '2000-09-01',
            ],
            [
                'name' => 'Relativity Space',
                'slug' => 'relativity-space',
                'website' => 'https://www.relativityspace.com',
                'linkedin_url' => 'https://www.linkedin.com/company/relativity-space',
                'description' => 'Building 3D-printed rockets with autonomous manufacturing.',
                'city' => 'Long Beach',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2015-01-01',
            ],
            [
                'name' => 'Stoke Space',
                'slug' => 'stoke-space',
                'website' => 'https://www.stokespace.com',
                'linkedin_url' => 'https://www.linkedin.com/company/stoke-space-technologies',
                'description' => 'Developing fully and rapidly reusable rocket systems.',
                'city' => 'Kent',
                'state' => 'WA',
                'country' => 'USA',
                'founded_date' => '2019-01-01',
            ],
            [
                'name' => 'Vast',
                'slug' => 'vast',
                'website' => 'https://www.vastspace.com',
                'linkedin_url' => 'https://www.linkedin.com/company/vastspace',
                'description' => 'Building the first commercial space station with artificial gravity.',
                'city' => 'Long Beach',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2021-01-01',
            ],
            [
                'name' => 'Intuitive Machines',
                'slug' => 'intuitive-machines',
                'website' => 'https://www.intuitivemachines.com',
                'linkedin_url' => 'https://www.linkedin.com/company/intuitive-machines',
                'description' => 'Space exploration company providing lunar landing and data services.',
                'city' => 'Houston',
                'state' => 'TX',
                'country' => 'USA',
                'founded_date' => '2013-01-01',
            ],
            [
                'name' => 'Orbit Fab',
                'slug' => 'orbit-fab',
                'website' => 'https://www.orbitfab.com',
                'linkedin_url' => 'https://www.linkedin.com/company/orbit-fab',
                'description' => 'Building in-space refueling infrastructure for satellites.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2018-01-01',
            ],
            [
                'name' => 'ABL Space Systems',
                'slug' => 'abl-space-systems',
                'website' => 'https://ablspacesystems.com',
                'linkedin_url' => 'https://www.linkedin.com/company/abl-space-systems',
                'description' => 'Low-cost launch services with containerized ground systems.',
                'city' => 'El Segundo',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2017-01-01',
            ],
            [
                'name' => 'Gravitics',
                'slug' => 'gravitics',
                'website' => 'https://gravitics.com',
                'linkedin_url' => 'https://www.linkedin.com/company/gravitics',
                'description' => 'Designing and manufacturing large space station modules.',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'USA',
                'founded_date' => '2021-01-01',
            ],

            // Biotech/Healthcare
            [
                'name' => 'Retro Biosciences',
                'slug' => 'retro-biosciences',
                'website' => 'https://retro.bio',
                'linkedin_url' => 'https://www.linkedin.com/company/retro-biosciences',
                'description' => 'Longevity research company working to extend healthy human lifespan.',
                'city' => 'Redwood City',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2021-01-01',
            ],
            [
                'name' => 'Mammoth Biosciences',
                'slug' => 'mammoth-biosciences',
                'website' => 'https://mammoth.bio',
                'linkedin_url' => 'https://www.linkedin.com/company/mammoth-biosciences',
                'description' => 'CRISPR-based platform for diagnostics and therapeutics.',
                'city' => 'Brisbane',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2017-01-01',
            ],
            [
                'name' => 'Cradle',
                'slug' => 'cradle',
                'website' => 'https://cradle.bio',
                'linkedin_url' => 'https://www.linkedin.com/company/cradlebio',
                'description' => 'AI platform for designing and optimizing proteins.',
                'city' => 'Amsterdam',
                'state' => null,
                'country' => 'Netherlands',
                'founded_date' => '2021-01-01',
            ],
            [
                'name' => 'Cortical Labs',
                'slug' => 'cortical-labs',
                'website' => 'https://corticallabs.com',
                'linkedin_url' => 'https://www.linkedin.com/company/cortical-labs',
                'description' => 'Building biological computing systems using human neurons.',
                'city' => 'Melbourne',
                'state' => 'VIC',
                'country' => 'Australia',
                'founded_date' => '2019-01-01',
            ],

            // Climate/Energy
            [
                'name' => 'Redwood Materials',
                'slug' => 'redwood-materials',
                'website' => 'https://www.redwoodmaterials.com',
                'linkedin_url' => 'https://www.linkedin.com/company/redwood-materials',
                'description' => 'Recycling lithium-ion batteries to create sustainable battery materials.',
                'city' => 'Carson City',
                'state' => 'NV',
                'country' => 'USA',
                'founded_date' => '2017-01-01',
            ],
            [
                'name' => 'Amp Robotics',
                'slug' => 'amp-robotics',
                'website' => 'https://www.amprobotics.com',
                'linkedin_url' => 'https://www.linkedin.com/company/amp-robotics',
                'description' => 'AI-powered robotic systems for recycling and waste sorting.',
                'city' => 'Louisville',
                'state' => 'CO',
                'country' => 'USA',
                'founded_date' => '2014-01-01',
            ],
            [
                'name' => 'Gridware',
                'slug' => 'gridware',
                'website' => 'https://www.gridware.io',
                'linkedin_url' => 'https://www.linkedin.com/company/gridware',
                'description' => 'Sensors and analytics for electrical grid monitoring and wildfire prevention.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2018-01-01',
            ],
            [
                'name' => 'Lumotive',
                'slug' => 'lumotive',
                'website' => 'https://www.lumotive.com',
                'linkedin_url' => 'https://www.linkedin.com/company/lumotive',
                'description' => 'Programmable beam-steering technology for lidar and optical sensing.',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'USA',
                'founded_date' => '2018-01-01',
            ],

            // Consumer/Social
            [
                'name' => 'Bluesky',
                'slug' => 'bluesky',
                'website' => 'https://bsky.social',
                'linkedin_url' => 'https://www.linkedin.com/company/bluesky-social',
                'description' => 'Decentralized social media platform built on the AT Protocol.',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'USA',
                'founded_date' => '2021-01-01',
            ],
            [
                'name' => 'Fizz',
                'slug' => 'fizz',
                'website' => 'https://fizzsocial.app',
                'linkedin_url' => 'https://www.linkedin.com/company/fizzsocial',
                'description' => 'Anonymous social platform for college students.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2021-01-01',
            ],

            // Infrastructure/DevTools
            [
                'name' => 'Parasail',
                'slug' => 'parasail',
                'website' => 'https://www.parasail.io',
                'linkedin_url' => 'https://www.linkedin.com/company/parasail-io',
                'description' => 'On-demand GPU cloud infrastructure for AI workloads.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2023-01-01',
            ],
            [
                'name' => 'Plural',
                'slug' => 'plural',
                'website' => 'https://www.plural.sh',
                'linkedin_url' => 'https://www.linkedin.com/company/pluralsh',
                'description' => 'Platform for deploying and managing Kubernetes applications.',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'founded_date' => '2021-01-01',
            ],
            [
                'name' => 'NeoLogic',
                'slug' => 'neologic',
                'website' => 'https://www.neologic.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/neologic-ai',
                'description' => 'Building energy-efficient CPUs optimized for AI inference.',
                'city' => 'Palo Alto',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2023-01-01',
            ],

            // Defense/Aerospace
            [
                'name' => 'Castelion',
                'slug' => 'castelion',
                'website' => 'https://www.castelion.com',
                'linkedin_url' => 'https://www.linkedin.com/company/castelion',
                'description' => 'Defense technology company building autonomous systems.',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2022-01-01',
            ],
            [
                'name' => 'Anduril Industries',
                'slug' => 'anduril-industries',
                'website' => 'https://www.anduril.com',
                'linkedin_url' => 'https://www.linkedin.com/company/anduril',
                'description' => 'Defense technology company building autonomous systems and AI.',
                'city' => 'Costa Mesa',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2017-01-01',
            ],

            // Additional AI/ML
            [
                'name' => 'Imbue',
                'slug' => 'imbue',
                'website' => 'https://imbue.com',
                'linkedin_url' => 'https://www.linkedin.com/company/imbue-ai',
                'description' => 'AI research company building systems that reason and code.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2021-01-01',
            ],
            [
                'name' => 'Adept',
                'slug' => 'adept-ai',
                'website' => 'https://www.adept.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/adaborai',
                'description' => 'Building AI agents that can take actions on computers.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2022-01-01',
            ],
            [
                'name' => 'Covariant',
                'slug' => 'covariant',
                'website' => 'https://covariant.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/covariant-ai',
                'description' => 'AI robotics company building universal AI for robots.',
                'city' => 'Emeryville',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2017-01-01',
            ],
            [
                'name' => 'Poolside',
                'slug' => 'poolside',
                'website' => 'https://www.poolside.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/poolside-ai',
                'description' => 'Building AI assistants specifically trained for software engineering.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2023-01-01',
            ],
            [
                'name' => 'Magic',
                'slug' => 'magic',
                'website' => 'https://magic.dev',
                'linkedin_url' => 'https://www.linkedin.com/company/magic-dev',
                'description' => 'AI coding assistant with massive context window capabilities.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2022-01-01',
            ],
            [
                'name' => 'Cognition',
                'slug' => 'cognition',
                'website' => 'https://www.cognition.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/cognition-ai',
                'description' => 'Creator of Devin, the AI software engineer.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2023-01-01',
            ],

            // Additional Notable Startups
            [
                'name' => 'Wiz',
                'slug' => 'wiz',
                'website' => 'https://www.wiz.io',
                'linkedin_url' => 'https://www.linkedin.com/company/wizsecurity',
                'description' => 'Cloud security platform providing unified visibility and risk assessment.',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'founded_date' => '2020-01-01',
            ],
            [
                'name' => 'Vanta',
                'slug' => 'vanta',
                'website' => 'https://www.vanta.com',
                'linkedin_url' => 'https://www.linkedin.com/company/vaboranta',
                'description' => 'Automated security and compliance platform for SOC 2, HIPAA, and more.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2018-01-01',
            ],
            [
                'name' => 'Anysphere',
                'slug' => 'anysphere',
                'website' => 'https://www.anysphere.co',
                'linkedin_url' => 'https://www.linkedin.com/company/anysphere',
                'description' => 'Building Cursor, an AI-powered code editor.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2022-01-01',
            ],
            [
                'name' => 'Flock Safety',
                'slug' => 'flock-safety',
                'website' => 'https://www.flocksafety.com',
                'linkedin_url' => 'https://www.linkedin.com/company/flock-safety',
                'description' => 'Public safety technology with license plate readers and community cameras.',
                'city' => 'Atlanta',
                'state' => 'GA',
                'country' => 'USA',
                'founded_date' => '2017-01-01',
            ],
            [
                'name' => 'Sardine',
                'slug' => 'sardine',
                'website' => 'https://www.sardine.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/sardine-ai',
                'description' => 'Fraud prevention and compliance platform for fintech companies.',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'founded_date' => '2020-01-01',
            ],
        ];

        foreach ($companies as $data) {
            Company::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }

        $this->command->info('Seeded '.count($companies).' companies from TechCrunch headlines.');
    }
}
