<?php

namespace Database\Seeders;

use App\Models\Company;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UnicornBackfillSeeder extends Seeder
{
    public function run(): void
    {
        $count = 0;
        $companies = [
            [
                'name' => 'SHEIN',
                'slug' => 'shein',
                'website' => 'https://shein.com',
                'description' => 'Consumer & Retail company. Valued at $66B.',
                'category' => 'consumer',
                'city' => null,
                'country' => 'Singapore',
            ],
            [
                'name' => 'Ripple',
                'slug' => 'ripple',
                'website' => 'https://ripple.com',
                'description' => 'Financial Services company. Valued at $40B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Safe Superintelligence',
                'slug' => 'safe-superintelligence',
                'website' => 'https://safesuperintelligence.com',
                'description' => 'Enterprise Tech company. Valued at $30B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Epic Games',
                'slug' => 'epic-games',
                'website' => 'https://epicgames.com',
                'description' => 'Media & Entertainment company. Valued at $22.5B.',
                'category' => 'consumer',
                'city' => 'Cary',
                'country' => 'USA',
            ],
            [
                'name' => 'Chobani',
                'slug' => 'chobani',
                'website' => 'https://chobani.com',
                'description' => 'Consumer & Retail company. Valued at $20B.',
                'category' => 'consumer',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Xiaohongshu',
                'slug' => 'xiaohongshu',
                'website' => 'https://xiaohongshu.com',
                'description' => 'Media & Entertainment company. Valued at $17B.',
                'category' => 'consumer',
                'city' => 'Shanghai',
                'country' => 'China',
            ],
            [
                'name' => 'Yuanfudao',
                'slug' => 'yuanfudao',
                'website' => 'https://yuanfudao.com',
                'description' => 'Consumer & Retail company. Valued at $15.5B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'DJI Innovations',
                'slug' => 'dji-innovations',
                'website' => 'https://djiinnovations.com',
                'description' => 'Industrials company. Valued at $15B.',
                'category' => 'enterprise',
                'city' => 'Shenzhen',
                'country' => 'China',
            ],
            [
                'name' => 'ClickHouse',
                'slug' => 'clickhouse',
                'website' => 'https://clickhouse.com',
                'description' => 'Enterprise Tech company. Valued at $15B.',
                'category' => 'enterprise',
                'city' => 'Portola Valley',
                'country' => 'USA',
            ],
            [
                'name' => 'Yuanqi Senlin',
                'slug' => 'yuanqi-senlin',
                'website' => 'https://yuanqisenlin.com',
                'description' => 'Consumer & Retail company. Valued at $15B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Trade Republic',
                'slug' => 'trade-republic',
                'website' => 'https://traderepublic.com',
                'description' => 'Financial Services company. Valued at $14.65B.',
                'category' => 'fintech',
                'city' => 'Berlin',
                'country' => 'Germany',
            ],
            [
                'name' => 'Skild AI',
                'slug' => 'skild-ai',
                'website' => 'https://skildai.com',
                'description' => 'Industrials company. Valued at $14B.',
                'category' => 'enterprise',
                'city' => 'Pittsburgh',
                'country' => 'USA',
            ],
            [
                'name' => 'OpenSea',
                'slug' => 'opensea',
                'website' => 'https://opensea.com',
                'description' => 'Media & Entertainment company. Valued at $13.3B.',
                'category' => 'consumer',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'JUUL Labs',
                'slug' => 'juul-labs',
                'website' => 'https://juullabs.com',
                'description' => 'Consumer & Retail company. Valued at $12B.',
                'category' => 'consumer',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Bitmain Technologies',
                'slug' => 'bitmain-technologies',
                'website' => 'https://bitmaintechnologies.com',
                'description' => 'Enterprise Tech company. Valued at $12B.',
                'category' => 'enterprise',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'GoodLeap',
                'slug' => 'goodleap',
                'website' => 'https://goodleap.com',
                'description' => 'Financial Services company. Valued at $12B.',
                'category' => 'fintech',
                'city' => 'Roseville',
                'country' => 'USA',
            ],
            [
                'name' => 'Xingsheng Selected',
                'slug' => 'xingsheng-selected',
                'website' => 'https://xingshengselected.com',
                'description' => 'Consumer & Retail company. Valued at $12B.',
                'category' => 'consumer',
                'city' => 'Changsha',
                'country' => 'China',
            ],
            [
                'name' => 'ZongMu Technology',
                'slug' => 'zongmu-technology',
                'website' => 'https://zongmutechnology.com',
                'description' => 'Industrials company. Valued at $11.4B.',
                'category' => 'enterprise',
                'city' => 'Shanghai',
                'country' => 'China',
            ],
            [
                'name' => 'Bending Spoons',
                'slug' => 'bending-spoons',
                'website' => 'https://bendingspoons.com',
                'description' => 'Consumer & Retail company. Valued at $11.71B.',
                'category' => 'consumer',
                'city' => 'Milan',
                'country' => 'Italy',
            ],
            [
                'name' => 'Global Switch',
                'slug' => 'global-switch',
                'website' => 'https://globalswitch.com',
                'description' => 'Enterprise Tech company. Valued at $11.1B.',
                'category' => 'enterprise',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'Bilt Rewards',
                'slug' => 'bilt-rewards',
                'website' => 'https://biltrewards.com',
                'description' => 'Financial Services company. Valued at $10.75B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Colossal',
                'slug' => 'colossal',
                'website' => 'https://colossal.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $10.2B.',
                'category' => 'healthcare',
                'city' => 'Austin',
                'country' => 'USA',
            ],
            [
                'name' => 'Huolala',
                'slug' => 'huolala',
                'website' => 'https://huolala.com',
                'description' => 'Industrials company. Valued at $10B.',
                'category' => 'enterprise',
                'city' => 'Guangzhou',
                'country' => 'China',
            ],
            [
                'name' => 'Thinking Machines Lab',
                'slug' => 'thinking-machines-lab',
                'website' => 'https://thinkingmachineslab.com',
                'description' => 'Enterprise Tech company. Valued at $10B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Crusoe',
                'slug' => 'crusoe',
                'website' => 'https://crusoe.com',
                'description' => 'Industrials company. Valued at $10B.',
                'category' => 'enterprise',
                'city' => 'Denver',
                'country' => 'USA',
            ],
            [
                'name' => 'Chehaoduo',
                'slug' => 'chehaoduo',
                'website' => 'https://chehaoduo.com',
                'description' => 'Consumer & Retail company. Valued at $10B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Digital Currency Group',
                'slug' => 'digital-currency-group',
                'website' => 'https://digitalcurrencygroup.com',
                'description' => 'Financial Services company. Valued at $10B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'KuCoin',
                'slug' => 'kucoin',
                'website' => 'https://kucoin.com',
                'description' => 'Financial Services company. Valued at $10B.',
                'category' => 'fintech',
                'city' => 'Victoria',
                'country' => 'Seychelles',
            ],
            [
                'name' => 'HEYTEA',
                'slug' => 'heytea',
                'website' => 'https://heytea.com',
                'description' => 'Consumer & Retail company. Valued at $9.28B.',
                'category' => 'consumer',
                'city' => 'Shenzhen',
                'country' => 'China',
            ],
            [
                'name' => 'Polymarket',
                'slug' => 'polymarket',
                'website' => 'https://polymarket.com',
                'description' => 'Financial Services company. Valued at $9B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Tanium',
                'slug' => 'tanium',
                'website' => 'https://tanium.com',
                'description' => 'Enterprise Tech company. Valued at $9B.',
                'category' => 'enterprise',
                'city' => 'Kirkland',
                'country' => 'USA',
            ],
            [
                'name' => 'OYO Rooms',
                'slug' => 'oyo-rooms',
                'website' => 'https://oyorooms.com',
                'description' => 'Consumer & Retail company. Valued at $9B.',
                'category' => 'consumer',
                'city' => 'Gurugram',
                'country' => 'India',
            ],
            [
                'name' => 'Chainalysis',
                'slug' => 'chainalysis',
                'website' => 'https://chainalysis.com',
                'description' => 'Financial Services company. Valued at $8.6B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'SumUp',
                'slug' => 'sumup',
                'website' => 'https://sumup.com',
                'description' => 'Financial Services company. Valued at $8.5B.',
                'category' => 'fintech',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'Bolt (Estonia)',
                'slug' => 'bolt-estonia',
                'website' => 'https://boltestonia.com',
                'description' => 'Industrials company. Valued at $8.4B.',
                'category' => 'enterprise',
                'city' => 'Tallinn',
                'country' => 'Estonia',
            ],
            [
                'name' => 'Tipalti',
                'slug' => 'tipalti',
                'website' => 'https://tipalti.com',
                'description' => 'Enterprise Tech company. Valued at $8.3B.',
                'category' => 'enterprise',
                'city' => 'San Mateo',
                'country' => 'USA',
            ],
            [
                'name' => 'Odoo',
                'slug' => 'odoo',
                'website' => 'https://odoo.com',
                'description' => 'Enterprise Tech company. Valued at $8.13B.',
                'category' => 'enterprise',
                'city' => 'Louvain-la-Neuve',
                'country' => 'Belgium',
            ],
            [
                'name' => 'Reflection AI',
                'slug' => 'reflection-ai',
                'website' => 'https://reflectionai.com',
                'description' => 'Enterprise Tech company. Valued at $8B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Airwallex',
                'slug' => 'airwallex',
                'website' => 'https://airwallex.com',
                'description' => 'Financial Services company. Valued at $8B.',
                'category' => 'fintech',
                'city' => 'Melbourne',
                'country' => 'Australia',
            ],
            [
                'name' => 'Fireblocks',
                'slug' => 'fireblocks',
                'website' => 'https://fireblocks.com',
                'description' => 'Financial Services company. Valued at $8B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'FalconX',
                'slug' => 'falconx',
                'website' => 'https://falconx.com',
                'description' => 'Financial Services company. Valued at $8B.',
                'category' => 'fintech',
                'city' => 'San Mateo',
                'country' => 'USA',
            ],
            [
                'name' => 'Caris',
                'slug' => 'caris',
                'website' => 'https://caris.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $7.83B.',
                'category' => 'healthcare',
                'city' => 'Irving',
                'country' => 'USA',
            ],
            [
                'name' => 'Zipline',
                'slug' => 'zipline',
                'website' => 'https://zipline.com',
                'description' => 'Industrials company. Valued at $7.6B.',
                'category' => 'enterprise',
                'city' => 'South San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Automattic',
                'slug' => 'automattic',
                'website' => 'https://automattic.com',
                'description' => 'Media & Entertainment company. Valued at $7.5B.',
                'category' => 'consumer',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Upgrade',
                'slug' => 'upgrade',
                'website' => 'https://upgrade.com',
                'description' => 'Financial Services company. Valued at $7.3B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Blockchain.com',
                'slug' => 'blockchain-com',
                'website' => 'https://blockchaincom.com',
                'description' => 'Financial Services company. Valued at $7B.',
                'category' => 'fintech',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'Wonder',
                'slug' => 'wonder',
                'website' => 'https://wonder.com',
                'description' => 'Consumer & Retail company. Valued at $7B.',
                'category' => 'consumer',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'We Doctor',
                'slug' => 'we-doctor',
                'website' => 'https://wedoctor.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $7B.',
                'category' => 'healthcare',
                'city' => 'Hangzhou',
                'country' => 'China',
            ],
            [
                'name' => 'ConsenSys',
                'slug' => 'consensys',
                'website' => 'https://consensys.com',
                'description' => 'Enterprise Tech company. Valued at $7B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Automation Anywhere',
                'slug' => 'automation-anywhere',
                'website' => 'https://automationanywhere.com',
                'description' => 'Enterprise Tech company. Valued at $6.8B.',
                'category' => 'enterprise',
                'city' => 'San Jose',
                'country' => 'USA',
            ],
            [
                'name' => 'PsiQuantum',
                'slug' => 'psiquantum',
                'website' => 'https://psiquantum.com',
                'description' => 'Enterprise Tech company. Valued at $7B.',
                'category' => 'enterprise',
                'city' => 'Palo Alto',
                'country' => 'USA',
            ],
            [
                'name' => 'Ziroom',
                'slug' => 'ziroom',
                'website' => 'https://ziroom.com',
                'description' => 'Consumer & Retail company. Valued at $6.6B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'SVOLT',
                'slug' => 'svolt',
                'website' => 'https://svolt.com',
                'description' => 'Industrials company. Valued at $6.51B.',
                'category' => 'enterprise',
                'city' => 'Changzhou',
                'country' => 'China',
            ],
            [
                'name' => 'National Stock Exchange of India',
                'slug' => 'national-stock-exchange-of-india',
                'website' => 'https://nationalstockexchangeofindia.com',
                'description' => 'Financial Services company. Valued at $6.5B.',
                'category' => 'fintech',
                'city' => 'Mumbai',
                'country' => 'India',
            ],
            [
                'name' => 'Mollie',
                'slug' => 'mollie',
                'website' => 'https://mollie.com',
                'description' => 'Financial Services company. Valued at $6.5B.',
                'category' => 'fintech',
                'city' => 'Amsterdam',
                'country' => 'Netherlands',
            ],
            [
                'name' => 'Doctolib',
                'slug' => 'doctolib',
                'website' => 'https://doctolib.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $6.4B.',
                'category' => 'healthcare',
                'city' => 'Paris',
                'country' => 'France',
            ],
            [
                'name' => 'DataRobot',
                'slug' => 'datarobot',
                'website' => 'https://datarobot.com',
                'description' => 'Enterprise Tech company. Valued at $6.3B.',
                'category' => 'enterprise',
                'city' => 'Boston',
                'country' => 'USA',
            ],
            [
                'name' => 'Black Unicorn Factory',
                'slug' => 'black-unicorn-factory',
                'website' => 'https://blackunicornfactory.com',
                'description' => 'Enterprise Tech company. Valued at $6.1B.',
                'category' => 'enterprise',
                'city' => 'Los Angeles',
                'country' => 'USA',
            ],
            [
                'name' => 'OpenEvidence',
                'slug' => 'openevidence',
                'website' => 'https://openevidence.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $6B.',
                'category' => 'healthcare',
                'city' => 'Cambridge',
                'country' => 'USA',
            ],
            [
                'name' => 'Cyera',
                'slug' => 'cyera',
                'website' => 'https://cyera.com',
                'description' => 'Enterprise Tech company. Valued at $9B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Commure',
                'slug' => 'commure',
                'website' => 'https://commure.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $6B.',
                'category' => 'healthcare',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'iCapital',
                'slug' => 'icapital',
                'website' => 'https://icapital.com',
                'description' => 'Financial Services company. Valued at $7.5B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => '6Sense',
                'slug' => '6sense',
                'website' => 'https://6sense.com',
                'description' => 'Enterprise Tech company. Valued at $5.2B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Attentive',
                'slug' => 'attentive',
                'website' => 'https://attentive.com',
                'description' => 'Enterprise Tech company. Valued at $5.99B.',
                'category' => 'enterprise',
                'city' => 'Hoboken',
                'country' => 'USA',
            ],
            [
                'name' => 'Easyhome',
                'slug' => 'easyhome',
                'website' => 'https://easyhome.com',
                'description' => 'Consumer & Retail company. Valued at $5.78B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Lianjia',
                'slug' => 'lianjia',
                'website' => 'https://lianjia.com',
                'description' => 'Financial Services company. Valued at $5.77B.',
                'category' => 'fintech',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Physical Intelligence',
                'slug' => 'physical-intelligence',
                'website' => 'https://physicalintelligence.com',
                'description' => 'Enterprise Tech company. Valued at $5.6B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Vuori',
                'slug' => 'vuori',
                'website' => 'https://vuori.com',
                'description' => 'Consumer & Retail company. Valued at $5.5B.',
                'category' => 'consumer',
                'city' => 'Carlsbad',
                'country' => 'USA',
            ],
            [
                'name' => 'RELEX',
                'slug' => 'relex',
                'website' => 'https://relex.com',
                'description' => 'Consumer & Retail company. Valued at $5.7B.',
                'category' => 'consumer',
                'city' => 'Helsinki',
                'country' => 'Finland',
            ],
            [
                'name' => 'Verkada',
                'slug' => 'verkada',
                'website' => 'https://verkada.com',
                'description' => 'Industrials company. Valued at $5.8B.',
                'category' => 'enterprise',
                'city' => 'San Mateo',
                'country' => 'USA',
            ],
            [
                'name' => 'The Boring Company',
                'slug' => 'the-boring-company',
                'website' => 'https://theboringcompany.com',
                'description' => 'Industrials company. Valued at $5.7B.',
                'category' => 'enterprise',
                'city' => 'Pflugerville',
                'country' => 'USA',
            ],
            [
                'name' => 'ContentSquare',
                'slug' => 'contentsquare',
                'website' => 'https://contentsquare.com',
                'description' => 'Enterprise Tech company. Valued at $5.6B.',
                'category' => 'enterprise',
                'city' => 'Paris',
                'country' => 'France',
            ],
            [
                'name' => 'Helsing',
                'slug' => 'helsing',
                'website' => 'https://helsing.com',
                'description' => 'Enterprise Tech company. Valued at $5.37B.',
                'category' => 'enterprise',
                'city' => 'Munich',
                'country' => 'Germany',
            ],
            [
                'name' => 'Collibra',
                'slug' => 'collibra',
                'website' => 'https://collibra.com',
                'description' => 'Enterprise Tech company. Valued at $5.25B.',
                'category' => 'enterprise',
                'city' => 'Brussels',
                'country' => 'Belgium',
            ],
            [
                'name' => 'NinjaOne',
                'slug' => 'ninjaone',
                'website' => 'https://ninjaone.com',
                'description' => 'Enterprise Tech company. Valued at $5B.',
                'category' => 'enterprise',
                'city' => 'Austin',
                'country' => 'USA',
            ],
            [
                'name' => 'Unconventional AI',
                'slug' => 'unconventional-ai',
                'website' => 'https://unconventionalai.com',
                'description' => 'Enterprise Tech company. Valued at $4.5B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Quince',
                'slug' => 'quince',
                'website' => 'https://quince.com',
                'description' => 'Enterprise Tech company. Valued at $4.5B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'OneTrust',
                'slug' => 'onetrust',
                'website' => 'https://onetrust.com',
                'description' => 'Enterprise Tech company. Valued at $4.5B.',
                'category' => 'enterprise',
                'city' => 'Atlanta',
                'country' => 'USA',
            ],
            [
                'name' => 'Fuse Energy',
                'slug' => 'fuse-energy',
                'website' => 'https://fuseenergy.com',
                'description' => 'Industrials company. Valued at $5B.',
                'category' => 'enterprise',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'QuintoAndar',
                'slug' => 'quintoandar',
                'website' => 'https://quintoandar.com',
                'description' => 'Financial Services company. Valued at $5.1B.',
                'category' => 'fintech',
                'city' => 'Campinas',
                'country' => 'Brazil',
            ],
            [
                'name' => 'C6 Bank',
                'slug' => 'c6-bank',
                'website' => 'https://c6bank.com',
                'description' => 'Financial Services company. Valued at $5.05B.',
                'category' => 'fintech',
                'city' => 'Sao Paulo',
                'country' => 'Brazil',
            ],
            [
                'name' => 'Howden Group Holdings',
                'slug' => 'howden-group-holdings',
                'website' => 'https://howdengroupholdings.com',
                'description' => 'Insurance company. Valued at $5B.',
                'category' => 'fintech',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'Metropolis',
                'slug' => 'metropolis',
                'website' => 'https://metropolis.com',
                'description' => 'Consumer & Retail company. Valued at $5B.',
                'category' => 'consumer',
                'city' => 'Chicago',
                'country' => 'USA',
            ],
            [
                'name' => 'SambaNova Systems',
                'slug' => 'sambanova-systems',
                'website' => 'https://sambanovasystems.com',
                'description' => 'Enterprise Tech company. Valued at $5B.',
                'category' => 'enterprise',
                'city' => 'Palo Alto',
                'country' => 'USA',
            ],
            [
                'name' => 'OakNorth Bank',
                'slug' => 'oaknorth-bank',
                'website' => 'https://oaknorthbank.com',
                'description' => 'Financial Services company. Valued at $5B.',
                'category' => 'fintech',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'Moon Active',
                'slug' => 'moon-active',
                'website' => 'https://moonactive.com',
                'description' => 'Media & Entertainment company. Valued at $5B.',
                'category' => 'consumer',
                'city' => 'Tel Aviv',
                'country' => 'Israel',
            ],
            [
                'name' => 'OfBusiness',
                'slug' => 'ofbusiness',
                'website' => 'https://ofbusiness.com',
                'description' => 'Industrials company. Valued at $5B.',
                'category' => 'enterprise',
                'city' => 'Gurgaon',
                'country' => 'India',
            ],
            [
                'name' => 'Qonto',
                'slug' => 'qonto',
                'website' => 'https://qonto.com',
                'description' => 'Enterprise Tech company. Valued at $5B.',
                'category' => 'enterprise',
                'city' => 'Paris',
                'country' => 'France',
            ],
            [
                'name' => 'Etched',
                'slug' => 'etched',
                'website' => 'https://etched.com',
                'description' => 'Industrials company. Valued at $5B.',
                'category' => 'enterprise',
                'city' => 'San Jose',
                'country' => 'USA',
            ],
            [
                'name' => 'Icertis',
                'slug' => 'icertis',
                'website' => 'https://icertis.com',
                'description' => 'Enterprise Tech company. Valued at $5B.',
                'category' => 'enterprise',
                'city' => 'Bellevue',
                'country' => 'USA',
            ],
            [
                'name' => 'Hopper',
                'slug' => 'hopper',
                'website' => 'https://hopper.com',
                'description' => 'Consumer & Retail company. Valued at $5B.',
                'category' => 'consumer',
                'city' => 'Montreal',
                'country' => 'Canada',
            ],
            [
                'name' => 'VerSe Innovation',
                'slug' => 'verse-innovation',
                'website' => 'https://verseinnovation.com',
                'description' => 'Media & Entertainment company. Valued at $5B.',
                'category' => 'consumer',
                'city' => 'Bengaluru',
                'country' => 'India',
            ],
            [
                'name' => 'Lenskart',
                'slug' => 'lenskart',
                'website' => 'https://lenskart.com',
                'description' => 'Consumer & Retail company. Valued at $7.9B.',
                'category' => 'consumer',
                'city' => 'Faridabad',
                'country' => 'India',
            ],
            [
                'name' => 'ShareChat',
                'slug' => 'sharechat',
                'website' => 'https://sharechat.com',
                'description' => 'Media & Entertainment company. Valued at $5B.',
                'category' => 'consumer',
                'city' => 'Bengaluru',
                'country' => 'India',
            ],
            [
                'name' => 'Coalition',
                'slug' => 'coalition',
                'website' => 'https://coalition.com',
                'description' => 'Insurance company. Valued at $5B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Reify Health',
                'slug' => 'reify-health',
                'website' => 'https://reifyhealth.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $4.8B.',
                'category' => 'healthcare',
                'city' => 'Boston',
                'country' => 'USA',
            ],
            [
                'name' => 'Chipone',
                'slug' => 'chipone',
                'website' => 'https://chipone.com',
                'description' => 'Industrials company. Valued at $4.73B.',
                'category' => 'enterprise',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'BetterUp',
                'slug' => 'betterup',
                'website' => 'https://betterup.com',
                'description' => 'Enterprise Tech company. Valued at $4.7B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'SonarSource',
                'slug' => 'sonarsource',
                'website' => 'https://sonarsource.com',
                'description' => 'Enterprise Tech company. Valued at $4.7B.',
                'category' => 'enterprise',
                'city' => 'Geneva',
                'country' => 'Switzerland',
            ],
            [
                'name' => 'SandboxAQ',
                'slug' => 'sandboxaq',
                'website' => 'https://sandboxaq.com',
                'description' => 'Enterprise Tech company. Valued at $5.6B.',
                'category' => 'enterprise',
                'city' => 'Palo Alto',
                'country' => 'USA',
            ],
            [
                'name' => 'Checkr',
                'slug' => 'checkr',
                'website' => 'https://checkr.com',
                'description' => 'Enterprise Tech company. Valued at $4.6B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Skims',
                'slug' => 'skims',
                'website' => 'https://skims.com',
                'description' => 'Consumer & Retail company. Valued at $5B.',
                'category' => 'consumer',
                'city' => 'Los Angeles',
                'country' => 'USA',
            ],
            [
                'name' => 'Lendable',
                'slug' => 'lendable',
                'website' => 'https://lendable.com',
                'description' => 'Financial Services company. Valued at $4.58B.',
                'category' => 'fintech',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'VIPKid',
                'slug' => 'vipkid',
                'website' => 'https://vipkid.com',
                'description' => 'Consumer & Retail company. Valued at $4.5B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Socure',
                'slug' => 'socure',
                'website' => 'https://socure.com',
                'description' => 'Financial Services company. Valued at $4.5B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'humansand',
                'slug' => 'humansand',
                'website' => 'https://humansand.com',
                'description' => 'Enterprise Tech company. Valued at $4.48B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Outreach',
                'slug' => 'outreach',
                'website' => 'https://outreach.com',
                'description' => 'Enterprise Tech company. Valued at $4.4B.',
                'category' => 'enterprise',
                'city' => 'Seattle',
                'country' => 'USA',
            ],
            [
                'name' => 'Lightmatter',
                'slug' => 'lightmatter',
                'website' => 'https://lightmatter.com',
                'description' => 'Enterprise Tech company. Valued at $4.4B.',
                'category' => 'enterprise',
                'city' => 'Mountain View',
                'country' => 'USA',
            ],
            [
                'name' => 'Guild Education',
                'slug' => 'guild-education',
                'website' => 'https://guildeducation.com',
                'description' => 'Enterprise Tech company. Valued at $4.4B.',
                'category' => 'enterprise',
                'city' => 'Denver',
                'country' => 'USA',
            ],
            [
                'name' => 'Arctic Wolf Networks',
                'slug' => 'arctic-wolf-networks',
                'website' => 'https://arcticwolfnetworks.com',
                'description' => 'Enterprise Tech company. Valued at $4.3B.',
                'category' => 'enterprise',
                'city' => 'Eden Prairie',
                'country' => 'USA',
            ],
            [
                'name' => 'Moonshot AI',
                'slug' => 'moonshot-ai',
                'website' => 'https://moonshotai.com',
                'description' => 'Consumer & Retail company. Valued at $4.3B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'OutSystems',
                'slug' => 'outsystems',
                'website' => 'https://outsystems.com',
                'description' => 'Enterprise Tech company. Valued at $4.3B.',
                'category' => 'enterprise',
                'city' => 'Boston',
                'country' => 'USA',
            ],
            [
                'name' => 'Erebor',
                'slug' => 'erebor',
                'website' => 'https://erebor.com',
                'description' => 'Financial Services company. Valued at $4.35B.',
                'category' => 'fintech',
                'city' => 'Columbus',
                'country' => 'USA',
            ],
            [
                'name' => 'Sorare',
                'slug' => 'sorare',
                'website' => 'https://sorare.com',
                'description' => 'Media & Entertainment company. Valued at $4.3B.',
                'category' => 'consumer',
                'city' => 'Paris',
                'country' => 'France',
            ],
            [
                'name' => 'Miaoshou Doctor',
                'slug' => 'miaoshou-doctor',
                'website' => 'https://miaoshoudoctor.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $4.25B.',
                'category' => 'healthcare',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'ThoughtSpot',
                'slug' => 'thoughtspot',
                'website' => 'https://thoughtspot.com',
                'description' => 'Enterprise Tech company. Valued at $4.2B.',
                'category' => 'enterprise',
                'city' => 'Sunnyvale',
                'country' => 'USA',
            ],
            [
                'name' => 'Globalization Partners',
                'slug' => 'globalization-partners',
                'website' => 'https://globalizationpartners.com',
                'description' => 'Enterprise Tech company. Valued at $4.2B.',
                'category' => 'enterprise',
                'city' => 'Boston',
                'country' => 'USA',
            ],
            [
                'name' => 'SSENSE',
                'slug' => 'ssense',
                'website' => 'https://ssense.com',
                'description' => 'Consumer & Retail company. Valued at $4.15B.',
                'category' => 'consumer',
                'city' => 'Montreal',
                'country' => 'Canada',
            ],
            [
                'name' => 'Dataminr',
                'slug' => 'dataminr',
                'website' => 'https://dataminr.com',
                'description' => 'Enterprise Tech company. Valued at $4.1B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Pennylane',
                'slug' => 'pennylane',
                'website' => 'https://pennylane.com',
                'description' => 'Enterprise Tech company. Valued at $4.08B.',
                'category' => 'enterprise',
                'city' => 'Paris',
                'country' => 'France',
            ],
            [
                'name' => 'BitPanda',
                'slug' => 'bitpanda',
                'website' => 'https://bitpanda.com',
                'description' => 'Financial Services company. Valued at $4.11B.',
                'category' => 'fintech',
                'city' => 'Vienna',
                'country' => 'Austria',
            ],
            [
                'name' => 'Weee!',
                'slug' => 'weee',
                'website' => 'https://weee.com',
                'description' => 'Consumer & Retail company. Valued at $4.1B.',
                'category' => 'consumer',
                'city' => 'Fremont',
                'country' => 'USA',
            ],
            [
                'name' => 'Base Power',
                'slug' => 'base-power',
                'website' => 'https://basepower.com',
                'description' => 'Industrials company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'Austin',
                'country' => 'USA',
            ],
            [
                'name' => 'Fireworks',
                'slug' => 'fireworks',
                'website' => 'https://fireworks.com',
                'description' => 'Enterprise Tech company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'Redwood City',
                'country' => 'USA',
            ],
            [
                'name' => 'AlphaSense',
                'slug' => 'alphasense',
                'website' => 'https://alphasense.com',
                'description' => 'Enterprise Tech company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Saronic Technologies',
                'slug' => 'saronic-technologies',
                'website' => 'https://saronictechnologies.com',
                'description' => 'Industrials company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'Austin',
                'country' => 'USA',
            ],
            [
                'name' => 'The Brandtech Group',
                'slug' => 'the-brandtech-group',
                'website' => 'https://thebrandtechgroup.com',
                'description' => 'Enterprise Tech company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'EON',
                'slug' => 'eon',
                'website' => 'https://eon.com',
                'description' => 'Enterprise Tech company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Houzz',
                'slug' => 'houzz',
                'website' => 'https://houzz.com',
                'description' => 'Consumer & Retail company. Valued at $4B.',
                'category' => 'consumer',
                'city' => 'Palo Alto',
                'country' => 'USA',
            ],
            [
                'name' => 'Yello Mobile',
                'slug' => 'yello-mobile',
                'website' => 'https://yellomobile.com',
                'description' => 'Consumer & Retail company. Valued at $4B.',
                'category' => 'consumer',
                'city' => 'Seoul',
                'country' => 'South Korea',
            ],
            [
                'name' => 'Fal',
                'slug' => 'fal',
                'website' => 'https://fal.com',
                'description' => 'Enterprise Tech company. Valued at $4.5B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'MEGVII',
                'slug' => 'megvii',
                'website' => 'https://megvii.com',
                'description' => 'Enterprise Tech company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Greensill',
                'slug' => 'greensill',
                'website' => 'https://greensill.com',
                'description' => 'Financial Services company. Valued at $4B.',
                'category' => 'fintech',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'Radiology Partners',
                'slug' => 'radiology-partners',
                'website' => 'https://radiologypartners.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $4B.',
                'category' => 'healthcare',
                'city' => 'El Segundo',
                'country' => 'USA',
            ],
            [
                'name' => 'Next Insurance',
                'slug' => 'next-insurance',
                'website' => 'https://nextinsurance.com',
                'description' => 'Insurance company. Valued at $4B.',
                'category' => 'fintech',
                'city' => 'Palo Alto',
                'country' => 'USA',
            ],
            [
                'name' => 'PointClickCare',
                'slug' => 'pointclickcare',
                'website' => 'https://pointclickcare.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $4B.',
                'category' => 'healthcare',
                'city' => 'Mississauga',
                'country' => 'Canada',
            ],
            [
                'name' => 'Clubhouse',
                'slug' => 'clubhouse',
                'website' => 'https://clubhouse.com',
                'description' => 'Media & Entertainment company. Valued at $4B.',
                'category' => 'consumer',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'BrowserStack',
                'slug' => 'browserstack',
                'website' => 'https://browserstack.com',
                'description' => 'Enterprise Tech company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'Dublin',
                'country' => 'Ireland',
            ],
            [
                'name' => 'Farmers Business Network',
                'slug' => 'farmers-business-network',
                'website' => 'https://farmersbusinessnetwork.com',
                'description' => 'Industrials company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'San Carlos',
                'country' => 'USA',
            ],
            [
                'name' => 'Branch',
                'slug' => 'branch',
                'website' => 'https://branch.com',
                'description' => 'Enterprise Tech company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'Redwood City',
                'country' => 'USA',
            ],
            [
                'name' => 'Aurora Solar',
                'slug' => 'aurora-solar',
                'website' => 'https://aurorasolar.com',
                'description' => 'Industrials company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Yuga Labs',
                'slug' => 'yuga-labs',
                'website' => 'https://yugalabs.com',
                'description' => 'Media & Entertainment company. Valued at $4B.',
                'category' => 'consumer',
                'city' => 'Miami',
                'country' => 'USA',
            ],
            [
                'name' => 'firmus',
                'slug' => 'firmus',
                'website' => 'https://firmus.com',
                'description' => 'Enterprise Tech company. Valued at $3.92B.',
                'category' => 'enterprise',
                'city' => 'St Leonards',
                'country' => 'Australia',
            ],
            [
                'name' => 'Medlinker',
                'slug' => 'medlinker',
                'website' => 'https://medlinker.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3.92B.',
                'category' => 'healthcare',
                'city' => 'Chengdu',
                'country' => 'China',
            ],
            [
                'name' => 'MessageBird',
                'slug' => 'messagebird',
                'website' => 'https://messagebird.com',
                'description' => 'Enterprise Tech company. Valued at $3.8B.',
                'category' => 'enterprise',
                'city' => 'Amsterdam',
                'country' => 'Netherlands',
            ],
            [
                'name' => 'Articulate',
                'slug' => 'articulate',
                'website' => 'https://articulate.com',
                'description' => 'Enterprise Tech company. Valued at $3.75B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Dutchie',
                'slug' => 'dutchie',
                'website' => 'https://dutchie.com',
                'description' => 'Consumer & Retail company. Valued at $3.75B.',
                'category' => 'consumer',
                'city' => 'Bend',
                'country' => 'USA',
            ],
            [
                'name' => 'Cohesity',
                'slug' => 'cohesity',
                'website' => 'https://cohesity.com',
                'description' => 'Enterprise Tech company. Valued at $3.7B.',
                'category' => 'enterprise',
                'city' => 'San Jose',
                'country' => 'USA',
            ],
            [
                'name' => 'Abba Platforms',
                'slug' => 'abba-platforms',
                'website' => 'https://abbaplatforms.com',
                'description' => 'Financial Services company. Valued at $3.7B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Dataiku',
                'slug' => 'dataiku',
                'website' => 'https://dataiku.com',
                'description' => 'Enterprise Tech company. Valued at $3.7B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Abogen',
                'slug' => 'abogen',
                'website' => 'https://abogen.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3.7B.',
                'category' => 'healthcare',
                'city' => 'Suzhou',
                'country' => 'China',
            ],
            [
                'name' => 'Harness',
                'slug' => 'harness',
                'website' => 'https://harness.com',
                'description' => 'Enterprise Tech company. Valued at $5.5B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'o9 Solutions',
                'slug' => 'o9-solutions',
                'website' => 'https://o9solutions.com',
                'description' => 'Enterprise Tech company. Valued at $3.7B.',
                'category' => 'enterprise',
                'city' => 'Dallas',
                'country' => 'USA',
            ],
            [
                'name' => 'Relativity',
                'slug' => 'relativity',
                'website' => 'https://relativity.com',
                'description' => 'Enterprise Tech company. Valued at $3.6B.',
                'category' => 'enterprise',
                'city' => 'Chicago',
                'country' => 'USA',
            ],
            [
                'name' => 'Course Hero',
                'slug' => 'course-hero',
                'website' => 'https://coursehero.com',
                'description' => 'Consumer & Retail company. Valued at $3.6B.',
                'category' => 'consumer',
                'city' => 'Redwood City',
                'country' => 'USA',
            ],
            [
                'name' => 'SpotOn',
                'slug' => 'spoton',
                'website' => 'https://spoton.com',
                'description' => 'Financial Services company. Valued at $3.6B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Otto Bock HealthCare',
                'slug' => 'otto-bock-healthcare',
                'website' => 'https://ottobockhealthcare.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3.52B.',
                'category' => 'healthcare',
                'city' => 'Duderstadt',
                'country' => 'Germany',
            ],
            [
                'name' => 'Hippocratic AI',
                'slug' => 'hippocratic-ai',
                'website' => 'https://hippocraticai.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3.5B.',
                'category' => 'healthcare',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Indigo Ag',
                'slug' => 'indigo-ag',
                'website' => 'https://indigoag.com',
                'description' => 'Industrials company. Valued at $3.5B.',
                'category' => 'enterprise',
                'city' => 'Boston',
                'country' => 'USA',
            ],
            [
                'name' => 'HyalRoute',
                'slug' => 'hyalroute',
                'website' => 'https://hyalroute.com',
                'description' => 'Industrials company. Valued at $3.5B.',
                'category' => 'enterprise',
                'city' => null,
                'country' => 'Singapore',
            ],
            [
                'name' => 'Mirakl',
                'slug' => 'mirakl',
                'website' => 'https://mirakl.com',
                'description' => 'Consumer & Retail company. Valued at $3.5B.',
                'category' => 'consumer',
                'city' => 'Paris',
                'country' => 'France',
            ],
            [
                'name' => 'Tekion',
                'slug' => 'tekion',
                'website' => 'https://tekion.com',
                'description' => 'Industrials company. Valued at $4B.',
                'category' => 'enterprise',
                'city' => 'San Ramon',
                'country' => 'USA',
            ],
            [
                'name' => 'GoStudent',
                'slug' => 'gostudent',
                'website' => 'https://gostudent.com',
                'description' => 'Consumer & Retail company. Valued at $3.5B.',
                'category' => 'consumer',
                'city' => 'Vienna',
                'country' => 'Austria',
            ],
            [
                'name' => 'Highspot',
                'slug' => 'highspot',
                'website' => 'https://highspot.com',
                'description' => 'Enterprise Tech company. Valued at $3.5B.',
                'category' => 'enterprise',
                'city' => 'Seattle',
                'country' => 'USA',
            ],
            [
                'name' => 'Handshake',
                'slug' => 'handshake',
                'website' => 'https://handshake.com',
                'description' => 'Enterprise Tech company. Valued at $3.5B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'ChargeBee Technologies',
                'slug' => 'chargebee-technologies',
                'website' => 'https://chargebeetechnologies.com',
                'description' => 'Financial Services company. Valued at $3.5B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Unacademy',
                'slug' => 'unacademy',
                'website' => 'https://unacademy.com',
                'description' => 'Consumer & Retail company. Valued at $3.44B.',
                'category' => 'consumer',
                'city' => 'Bengaluru',
                'country' => 'India',
            ],
            [
                'name' => 'Upstox',
                'slug' => 'upstox',
                'website' => 'https://upstox.com',
                'description' => 'Financial Services company. Valued at $3.4B.',
                'category' => 'fintech',
                'city' => 'Mumbai',
                'country' => 'India',
            ],
            [
                'name' => 'Improbable',
                'slug' => 'improbable',
                'website' => 'https://improbable.com',
                'description' => 'Media & Entertainment company. Valued at $3.36B.',
                'category' => 'consumer',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'Youxia Motors',
                'slug' => 'youxia-motors',
                'website' => 'https://youxiamotors.com',
                'description' => 'Industrials company. Valued at $3.35B.',
                'category' => 'enterprise',
                'city' => 'Shanghai',
                'country' => 'China',
            ],
            [
                'name' => 'Starburst',
                'slug' => 'starburst',
                'website' => 'https://starburst.com',
                'description' => 'Enterprise Tech company. Valued at $3.35B.',
                'category' => 'enterprise',
                'city' => 'Boston',
                'country' => 'USA',
            ],
            [
                'name' => 'Sila',
                'slug' => 'sila',
                'website' => 'https://sila.com',
                'description' => 'Industrials company. Valued at $3.3B.',
                'category' => 'enterprise',
                'city' => 'Alameda',
                'country' => 'USA',
            ],
            [
                'name' => 'Tabby',
                'slug' => 'tabby',
                'website' => 'https://tabby.com',
                'description' => 'Financial Services company. Valued at $4.5B.',
                'category' => 'fintech',
                'city' => 'Dubai',
                'country' => 'UAE',
            ],
            [
                'name' => 'Kurly',
                'slug' => 'kurly',
                'website' => 'https://kurly.com',
                'description' => 'Consumer & Retail company. Valued at $3.3B.',
                'category' => 'consumer',
                'city' => 'Seoul',
                'country' => 'South Korea',
            ],
            [
                'name' => 'Cars24',
                'slug' => 'cars24',
                'website' => 'https://cars24.com',
                'description' => 'Industrials company. Valued at $3.3B.',
                'category' => 'enterprise',
                'city' => 'Gurgaon',
                'country' => 'India',
            ],
            [
                'name' => 'Judi Health',
                'slug' => 'judi-health',
                'website' => 'https://judihealth.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3.25B.',
                'category' => 'healthcare',
                'city' => 'New Jersey',
                'country' => 'USA',
            ],
            [
                'name' => 'Black Forest Labs',
                'slug' => 'black-forest-labs',
                'website' => 'https://blackforestlabs.com',
                'description' => 'Enterprise Tech company. Valued at $3.25B.',
                'category' => 'enterprise',
                'city' => 'Wilmington',
                'country' => 'USA',
            ],
            [
                'name' => 'BlockDaemon',
                'slug' => 'blockdaemon',
                'website' => 'https://blockdaemon.com',
                'description' => 'Financial Services company. Valued at $3.25B.',
                'category' => 'fintech',
                'city' => 'Los Angeles',
                'country' => 'USA',
            ],
            [
                'name' => 'Dadi Cinema',
                'slug' => 'dadi-cinema',
                'website' => 'https://dadicinema.com',
                'description' => 'Media & Entertainment company. Valued at $3.24B.',
                'category' => 'consumer',
                'city' => 'Shenzhen',
                'country' => 'China',
            ],
            [
                'name' => 'Thumbtack',
                'slug' => 'thumbtack',
                'website' => 'https://thumbtack.com',
                'description' => 'Consumer & Retail company. Valued at $3.2B.',
                'category' => 'consumer',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Cedar',
                'slug' => 'cedar',
                'website' => 'https://cedar.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3.2B.',
                'category' => 'healthcare',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Eruditus Executive Education',
                'slug' => 'eruditus-executive-education',
                'website' => 'https://eruditusexecutiveeducation.com',
                'description' => 'Enterprise Tech company. Valued at $3.1B.',
                'category' => 'enterprise',
                'city' => 'Mumbai',
                'country' => 'India',
            ],
            [
                'name' => 'K2 Space',
                'slug' => 'k2-space',
                'website' => 'https://k2space.com',
                'description' => 'Industrials company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'Torrance',
                'country' => 'USA',
            ],
            [
                'name' => 'Parloa',
                'slug' => 'parloa',
                'website' => 'https://parloa.com',
                'description' => 'Enterprise Tech company. Valued at $1B.',
                'category' => 'enterprise',
                'city' => 'Berlin',
                'country' => 'Germany',
            ],
            [
                'name' => 'Blockstream',
                'slug' => 'blockstream',
                'website' => 'https://blockstream.com',
                'description' => 'Financial Services company. Valued at $3.2B.',
                'category' => 'fintech',
                'city' => 'Vancouver',
                'country' => 'Canada',
            ],
            [
                'name' => 'Decart',
                'slug' => 'decart',
                'website' => 'https://decart.com',
                'description' => 'Enterprise Tech company. Valued at $3.21B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Addepar',
                'slug' => 'addepar',
                'website' => 'https://addepar.com',
                'description' => 'Financial Services company. Valued at $3.25B.',
                'category' => 'fintech',
                'city' => 'Mountain View',
                'country' => 'USA',
            ],
            [
                'name' => 'Innovaccer',
                'slug' => 'innovaccer',
                'website' => 'https://innovaccer.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3.45B.',
                'category' => 'healthcare',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'HighRadius',
                'slug' => 'highradius',
                'website' => 'https://highradius.com',
                'description' => 'Financial Services company. Valued at $3.1B.',
                'category' => 'fintech',
                'city' => 'Houston',
                'country' => 'USA',
            ],
            [
                'name' => 'Nuvemshop',
                'slug' => 'nuvemshop',
                'website' => 'https://nuvemshop.com',
                'description' => 'Consumer & Retail company. Valued at $3.1B.',
                'category' => 'consumer',
                'city' => 'Sao Paulo',
                'country' => 'Brazil',
            ],
            [
                'name' => 'LayerZero Labs',
                'slug' => 'layerzero-labs',
                'website' => 'https://layerzerolabs.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Filevine',
                'slug' => 'filevine',
                'website' => 'https://filevine.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'Salt Lake City',
                'country' => 'USA',
            ],
            [
                'name' => 'Clio',
                'slug' => 'clio',
                'website' => 'https://clio.com',
                'description' => 'Enterprise Tech company. Valued at $5B.',
                'category' => 'enterprise',
                'city' => 'Burnaby',
                'country' => 'Canada',
            ],
            [
                'name' => 'Zhipu AI',
                'slug' => 'zhipu-ai',
                'website' => 'https://zhipuai.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Nord Security',
                'slug' => 'nord-security',
                'website' => 'https://nordsecurity.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'Vilnius',
                'country' => 'Lithuania',
            ],
            [
                'name' => 'Yixia',
                'slug' => 'yixia',
                'website' => 'https://yixia.com',
                'description' => 'Media & Entertainment company. Valued at $3B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Traveloka',
                'slug' => 'traveloka',
                'website' => 'https://traveloka.com',
                'description' => 'Consumer & Retail company. Valued at $3B.',
                'category' => 'consumer',
                'city' => 'Jakarta',
                'country' => 'Indonesia',
            ],
            [
                'name' => 'Monad Labs',
                'slug' => 'monad-labs',
                'website' => 'https://monadlabs.com',
                'description' => 'Financial Services company. Valued at $3B.',
                'category' => 'fintech',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'SouChe Holdings',
                'slug' => 'souche-holdings',
                'website' => 'https://soucheholdings.com',
                'description' => 'Industrials company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'Hangzhou',
                'country' => 'China',
            ],
            [
                'name' => 'BGL Group',
                'slug' => 'bgl-group',
                'website' => 'https://bglgroup.com',
                'description' => 'Insurance company. Valued at $3B.',
                'category' => 'fintech',
                'city' => 'Peterborough',
                'country' => 'UK',
            ],
            [
                'name' => 'Zuoyebang',
                'slug' => 'zuoyebang',
                'website' => 'https://zuoyebang.com',
                'description' => 'Consumer & Retail company. Valued at $3B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Saviynt',
                'slug' => 'saviynt',
                'website' => 'https://saviynt.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'El Segundo',
                'country' => 'USA',
            ],
            [
                'name' => 'FlixMobility',
                'slug' => 'flixmobility',
                'website' => 'https://flixmobility.com',
                'description' => 'Industrials company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'Munich',
                'country' => 'Germany',
            ],
            [
                'name' => 'Wildlife Studios',
                'slug' => 'wildlife-studios',
                'website' => 'https://wildlifestudios.com',
                'description' => 'Media & Entertainment company. Valued at $3B.',
                'category' => 'consumer',
                'city' => 'Sao Paulo',
                'country' => 'Brazil',
            ],
            [
                'name' => 'ApplyBoard',
                'slug' => 'applyboard',
                'website' => 'https://applyboard.com',
                'description' => 'Consumer & Retail company. Valued at $3.2B.',
                'category' => 'consumer',
                'city' => 'Kitchener',
                'country' => 'Canada',
            ],
            [
                'name' => 'Forter',
                'slug' => 'forter',
                'website' => 'https://forter.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'BlockFi',
                'slug' => 'blockfi',
                'website' => 'https://blockfi.com',
                'description' => 'Financial Services company. Valued at $3B.',
                'category' => 'fintech',
                'city' => 'Jersey City',
                'country' => 'USA',
            ],
            [
                'name' => 'ActiveCampaign',
                'slug' => 'activecampaign',
                'website' => 'https://activecampaign.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'Chicago',
                'country' => 'USA',
            ],
            [
                'name' => 'CMR Surgical',
                'slug' => 'cmr-surgical',
                'website' => 'https://cmrsurgical.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3B.',
                'category' => 'healthcare',
                'city' => 'Cambridge',
                'country' => 'UK',
            ],
            [
                'name' => 'Lucid Software',
                'slug' => 'lucid-software',
                'website' => 'https://lucidsoftware.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'South Jordan',
                'country' => 'USA',
            ],
            [
                'name' => 'Age of Learning',
                'slug' => 'age-of-learning',
                'website' => 'https://ageoflearning.com',
                'description' => 'Consumer & Retail company. Valued at $3B.',
                'category' => 'consumer',
                'city' => 'Glendale',
                'country' => 'USA',
            ],
            [
                'name' => 'Zetwerk',
                'slug' => 'zetwerk',
                'website' => 'https://zetwerk.com',
                'description' => 'Industrials company. Valued at $3.1B.',
                'category' => 'enterprise',
                'city' => 'Bengaluru',
                'country' => 'India',
            ],
            [
                'name' => 'Carbon Health',
                'slug' => 'carbon-health',
                'website' => 'https://carbonhealth.com',
                'description' => 'Healthcare & Life Sciences company. Valued at $3B.',
                'category' => 'healthcare',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Seismic',
                'slug' => 'seismic',
                'website' => 'https://seismic.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'San Diego',
                'country' => 'USA',
            ],
            [
                'name' => 'Sky Mavis',
                'slug' => 'sky-mavis',
                'website' => 'https://skymavis.com',
                'description' => 'Media & Entertainment company. Valued at $3B.',
                'category' => 'consumer',
                'city' => 'Ho Chi Minh City',
                'country' => 'Vietnam',
            ],
            [
                'name' => 'TradingView',
                'slug' => 'tradingview',
                'website' => 'https://tradingview.com',
                'description' => 'Financial Services company. Valued at $3B.',
                'category' => 'fintech',
                'city' => 'Westerville',
                'country' => 'USA',
            ],
            [
                'name' => 'Rokt',
                'slug' => 'rokt',
                'website' => 'https://rokt.com',
                'description' => 'Consumer & Retail company. Valued at $3.5B.',
                'category' => 'consumer',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Via',
                'slug' => 'via',
                'website' => 'https://via.com',
                'description' => 'Industrials company. Valued at $3.5B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Anchorage Digital',
                'slug' => 'anchorage-digital',
                'website' => 'https://anchoragedigital.com',
                'description' => 'Financial Services company. Valued at $3B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Inxeption',
                'slug' => 'inxeption',
                'website' => 'https://inxeption.com',
                'description' => 'Industrials company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Cross River Bank',
                'slug' => 'cross-river-bank',
                'website' => 'https://crossriverbank.com',
                'description' => 'Financial Services company. Valued at $3B.',
                'category' => 'fintech',
                'city' => 'Fort Lee',
                'country' => 'USA',
            ],
            [
                'name' => 'TERMINUS Technology',
                'slug' => 'terminus-technology',
                'website' => 'https://terminustechnology.com',
                'description' => 'Industrials company. Valued at $2.96B.',
                'category' => 'enterprise',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Kraken',
                'slug' => 'kraken',
                'website' => 'https://kraken.com',
                'description' => 'Financial Services company. Valued at $2.92B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Workrise',
                'slug' => 'workrise',
                'website' => 'https://workrise.com',
                'description' => 'Industrials company. Valued at $2.9B.',
                'category' => 'enterprise',
                'city' => 'Austin',
                'country' => 'USA',
            ],
            [
                'name' => 'BharatPe',
                'slug' => 'bharatpe',
                'website' => 'https://bharatpe.com',
                'description' => 'Financial Services company. Valued at $2.85B.',
                'category' => 'fintech',
                'city' => 'New Delhi',
                'country' => 'India',
            ],
            [
                'name' => 'Gokin Solar',
                'slug' => 'gokin-solar',
                'website' => 'https://gokinsolar.com',
                'description' => 'Industrials company. Valued at $2.88B.',
                'category' => 'enterprise',
                'city' => 'Zhuhai',
                'country' => 'China',
            ],
            [
                'name' => 'DriveWealth',
                'slug' => 'drivewealth',
                'website' => 'https://drivewealth.com',
                'description' => 'Financial Services company. Valued at $2.85B.',
                'category' => 'fintech',
                'city' => 'Chatham',
                'country' => 'USA',
            ],
            [
                'name' => 'ICEYE',
                'slug' => 'iceye',
                'website' => 'https://iceye.com',
                'description' => 'Enterprise Tech company. Valued at $2.8B.',
                'category' => 'enterprise',
                'city' => 'Espoo',
                'country' => 'Finland',
            ],
            [
                'name' => 'Meicai',
                'slug' => 'meicai',
                'website' => 'https://meicai.com',
                'description' => 'Consumer & Retail company. Valued at $2.8B.',
                'category' => 'consumer',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Nutrabolt',
                'slug' => 'nutrabolt',
                'website' => 'https://nutrabolt.com',
                'description' => 'Consumer & Retail company. Valued at $2.79B.',
                'category' => 'consumer',
                'city' => 'Austin',
                'country' => 'USA',
            ],
            [
                'name' => 'Baichuan AI',
                'slug' => 'baichuan-ai',
                'website' => 'https://baichuanai.com',
                'description' => 'Enterprise Tech company. Valued at $2.77B.',
                'category' => 'enterprise',
                'city' => 'Beijing',
                'country' => 'China',
            ],
            [
                'name' => 'Abridge',
                'slug' => 'abridge',
                'website' => 'https://abridge.com',
                'description' => 'Enterprise Tech company. Valued at $2.75B.',
                'category' => 'enterprise',
                'city' => 'Pittsburgh',
                'country' => 'USA',
            ],
            [
                'name' => 'Hozon Auto',
                'slug' => 'hozon-auto',
                'website' => 'https://hozonauto.com',
                'description' => 'Industrials company. Valued at $3.95B.',
                'category' => 'enterprise',
                'city' => 'Shanghai',
                'country' => 'China',
            ],
            [
                'name' => 'Tradeshift',
                'slug' => 'tradeshift',
                'website' => 'https://tradeshift.com',
                'description' => 'Enterprise Tech company. Valued at $2.7B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'TravelPerk',
                'slug' => 'travelperk',
                'website' => 'https://travelperk.com',
                'description' => 'Enterprise Tech company. Valued at $2.7B.',
                'category' => 'enterprise',
                'city' => 'Barcelona',
                'country' => 'Spain',
            ],
            [
                'name' => 'Nextiva',
                'slug' => 'nextiva',
                'website' => 'https://nextiva.com',
                'description' => 'Enterprise Tech company. Valued at $2.7B.',
                'category' => 'enterprise',
                'city' => 'Scottsdale',
                'country' => 'USA',
            ],
            [
                'name' => 'Tridge',
                'slug' => 'tridge',
                'website' => 'https://tridge.com',
                'description' => 'Industrials company. Valued at $2.7B.',
                'category' => 'enterprise',
                'city' => 'Seoul',
                'country' => 'South Korea',
            ],
            [
                'name' => 'Starling Bank',
                'slug' => 'starling-bank',
                'website' => 'https://starlingbank.com',
                'description' => 'Financial Services company. Valued at $2.69B.',
                'category' => 'fintech',
                'city' => 'London',
                'country' => 'UK',
            ],
            [
                'name' => 'BackBase',
                'slug' => 'backbase',
                'website' => 'https://backbase.com',
                'description' => 'Financial Services company. Valued at $2.66B.',
                'category' => 'fintech',
                'city' => 'Amsterdam',
                'country' => 'Netherlands',
            ],
            [
                'name' => 'ManoMano',
                'slug' => 'manomano',
                'website' => 'https://manomano.com',
                'description' => 'Consumer & Retail company. Valued at $2.6B.',
                'category' => 'consumer',
                'city' => 'Paris',
                'country' => 'France',
            ],
            [
                'name' => 'Sourcegraph',
                'slug' => 'sourcegraph',
                'website' => 'https://sourcegraph.com',
                'description' => 'Enterprise Tech company. Valued at $2.62B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Pendo',
                'slug' => 'pendo',
                'website' => 'https://pendo.com',
                'description' => 'Enterprise Tech company. Valued at $2.6B.',
                'category' => 'enterprise',
                'city' => 'Raleigh',
                'country' => 'USA',
            ],
            [
                'name' => 'Plume',
                'slug' => 'plume',
                'website' => 'https://plume.com',
                'description' => 'Industrials company. Valued at $2.6B.',
                'category' => 'enterprise',
                'city' => 'Palo Alto',
                'country' => 'USA',
            ],
            [
                'name' => 'Moglix',
                'slug' => 'moglix',
                'website' => 'https://moglix.com',
                'description' => 'Industrials company. Valued at $2.6B.',
                'category' => 'enterprise',
                'city' => null,
                'country' => 'Singapore',
            ],
            [
                'name' => 'JumpCloud',
                'slug' => 'jumpcloud',
                'website' => 'https://jumpcloud.com',
                'description' => 'Enterprise Tech company. Valued at $2.62B.',
                'category' => 'enterprise',
                'city' => 'Louisville',
                'country' => 'USA',
            ],
            [
                'name' => 'Unico',
                'slug' => 'unico',
                'website' => 'https://unico.com',
                'description' => 'Enterprise Tech company. Valued at $2.6B.',
                'category' => 'enterprise',
                'city' => 'Sao Paulo',
                'country' => 'Brazil',
            ],
            [
                'name' => 'JUST Egg',
                'slug' => 'just-egg',
                'website' => 'https://justegg.com',
                'description' => 'Consumer & Retail company. Valued at $2.59B.',
                'category' => 'consumer',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Peregrine',
                'slug' => 'peregrine',
                'website' => 'https://peregrine.com',
                'description' => 'Enterprise Tech company. Valued at $2.5B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'n8n',
                'slug' => 'n8n',
                'website' => 'https://n8n.com',
                'description' => 'Enterprise Tech company. Valued at $2.5B.',
                'category' => 'enterprise',
                'city' => 'Berlin',
                'country' => 'Germany',
            ],
            [
                'name' => 'Lambda Labs',
                'slug' => 'lambda-labs',
                'website' => 'https://lambdalabs.com',
                'description' => 'Enterprise Tech company. Valued at $2.5B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Jetti Resources',
                'slug' => 'jetti-resources',
                'website' => 'https://jettiresources.com',
                'description' => 'Industrials company. Valued at $2.5B.',
                'category' => 'enterprise',
                'city' => 'Boulder',
                'country' => 'USA',
            ],
            [
                'name' => 'Claroty',
                'slug' => 'claroty',
                'website' => 'https://claroty.com',
                'description' => 'Enterprise Tech company. Valued at $3B.',
                'category' => 'enterprise',
                'city' => 'New York',
                'country' => 'USA',
            ],
            [
                'name' => 'Vista Global',
                'slug' => 'vista-global',
                'website' => 'https://vistaglobal.com',
                'description' => 'Industrials company. Valued at $2.5B.',
                'category' => 'enterprise',
                'city' => 'Dubai',
                'country' => 'UAE',
            ],
            [
                'name' => 'BYTON',
                'slug' => 'byton',
                'website' => 'https://byton.com',
                'description' => 'Industrials company. Valued at $2.5B.',
                'category' => 'enterprise',
                'city' => 'Nanjing',
                'country' => 'China',
            ],
            [
                'name' => 'Side',
                'slug' => 'side',
                'website' => 'https://side.com',
                'description' => 'Financial Services company. Valued at $2.5B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Infra.Market',
                'slug' => 'infra-market',
                'website' => 'https://inframarket.com',
                'description' => 'Industrials company. Valued at $2.78B.',
                'category' => 'enterprise',
                'city' => 'Thane',
                'country' => 'India',
            ],
            [
                'name' => 'Varo Bank',
                'slug' => 'varo-bank',
                'website' => 'https://varobank.com',
                'description' => 'Financial Services company. Valued at $2.5B.',
                'category' => 'fintech',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
            [
                'name' => 'Aura',
                'slug' => 'aura',
                'website' => 'https://aura.com',
                'description' => 'Consumer & Retail company. Valued at $2.5B.',
                'category' => 'consumer',
                'city' => 'Burlington',
                'country' => 'USA',
            ],
            [
                'name' => 'TensTorrent',
                'slug' => 'tenstorrent',
                'website' => 'https://tenstorrent.com',
                'description' => 'Enterprise Tech company. Valued at $2.6B.',
                'category' => 'enterprise',
                'city' => 'Toronto',
                'country' => 'Canada',
            ],
            [
                'name' => 'Distyl AI',
                'slug' => 'distyl-ai',
                'website' => 'https://distylai.com',
                'description' => 'Enterprise Tech company. Valued at $1.8B.',
                'category' => 'enterprise',
                'city' => 'San Francisco',
                'country' => 'USA',
            ],
        ];

        foreach ($companies as $data) {
            $existing = Company::where('name', $data['name'])
                ->orWhere('slug', $data['slug'])
                ->first();

            if (!$existing) {
                Company::create($data);
                $count++;
            }
        }

        $this->command->info("Unicorn backfill complete: {$count} new companies added.");
        $this->command->info("Total companies: " . Company::count());
    }
}

